import {hasFeature} from './user-access.js';
import {sharedAgentImport,staffImportIdentity} from './staff-whatsapp-reuse.js';
import {agentAppearance} from './agent-appearance.js';
import {fiveRingsRequirement,postponeFiveRings} from './five-rings-onboarding.js';
import {reserveFairLead} from './queue-fairness.js';
import {listObligations,reportPayment} from './marketing-obligations.js';
import {classifySale,ratesSchema} from './affiliate-rates.js';
import {isUSPhone,codes} from './us-area-codes.js';
import {contactBridge} from './affiliate-whatsapp.js';
export const stages=['Importados','1ª chamada','2ª chamada','Interesse','Reunião agendada','Follow-up','Aplicação','Aplicado','Emitida','Recusada','Sem interesse','Já tem seguro','Agente'];
const terminal=new Set(['Recusada','Sem interesse','Já tem seguro','Agente','Cliente ativo']);
const json=(x,status=200)=>Response.json(x,{status,headers:{'cache-control':'no-store'}});
export async function leadSchema(env){
 for(const sql of [
 "CREATE TABLE IF NOT EXISTS staffOnboarding (owner TEXT PRIMARY KEY,kind TEXT NOT NULL,phone TEXT NOT NULL,avatar TEXT NOT NULL,profileSaved INTEGER NOT NULL DEFAULT 0,completed INTEGER NOT NULL DEFAULT 0,updatedAt TEXT DEFAULT CURRENT_TIMESTAMP)",
 "CREATE TABLE IF NOT EXISTS agentRegistrationNumbers(owner TEXT PRIMARY KEY,number TEXT,pending INTEGER NOT NULL DEFAULT 1,nextPromptAt INTEGER NOT NULL DEFAULT 0,updatedAt TEXT DEFAULT CURRENT_TIMESTAMP)",
 "CREATE TABLE IF NOT EXISTS staffContactImports (owner TEXT PRIMARY KEY,cursor INTEGER NOT NULL DEFAULT 0,total INTEGER NOT NULL DEFAULT 0,state TEXT NOT NULL DEFAULT 'connecting',consentedAt TEXT DEFAULT CURRENT_TIMESTAMP)",
 "CREATE TABLE IF NOT EXISTS centralLeads (phone TEXT PRIMARY KEY,name TEXT NOT NULL,isUS INTEGER NOT NULL,stage TEXT NOT NULL DEFAULT 'Importados',suppressed INTEGER NOT NULL DEFAULT 0,leaseOwner TEXT,leaseUntil INTEGER NOT NULL DEFAULT 0,createdAt TEXT DEFAULT CURRENT_TIMESTAMP,updatedAt TEXT DEFAULT CURRENT_TIMESTAMP)",
 "CREATE TABLE IF NOT EXISTS centralLeadSources (phone TEXT NOT NULL,owner TEXT NOT NULL,kind TEXT NOT NULL,sourceName TEXT NOT NULL,sourceEmail TEXT NOT NULL,groupsJson TEXT NOT NULL DEFAULT '[]',priority INTEGER NOT NULL DEFAULT 0,createdAt TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(phone,owner))",
 "CREATE TABLE IF NOT EXISTS centralLeadAssignments (phone TEXT NOT NULL,agent TEXT NOT NULL,assignedBy TEXT NOT NULL,nextAt INTEGER NOT NULL DEFAULT 0,createdAt TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(phone,agent))",
 "CREATE TABLE IF NOT EXISTS centralLeadOutcomes (id INTEGER PRIMARY KEY AUTOINCREMENT,phone TEXT NOT NULL,agent TEXT NOT NULL,response TEXT NOT NULL,attempts INTEGER NOT NULL,stage TEXT NOT NULL,note TEXT NOT NULL,appointment TEXT,createdAt TEXT DEFAULT CURRENT_TIMESTAMP)",
 "CREATE TABLE IF NOT EXISTS centralAgentExcludedGroups(owner TEXT NOT NULL,groupId TEXT NOT NULL,PRIMARY KEY(owner,groupId))",
 "CREATE TABLE IF NOT EXISTS centralExcludedGroups (groupId TEXT PRIMARY KEY,name TEXT NOT NULL,excludedBy TEXT NOT NULL,createdAt TEXT DEFAULT CURRENT_TIMESTAMP)",
 'CREATE INDEX IF NOT EXISTS centralLeadQueue ON centralLeadAssignments(agent,nextAt)',
 'CREATE INDEX IF NOT EXISTS centralLeadSourceOwner ON centralLeadSources(owner,phone)',
 'CREATE INDEX IF NOT EXISTS centralLeadOutcomePhone ON centralLeadOutcomes(phone,id)',
 'CREATE INDEX IF NOT EXISTS centralLeadCategory ON centralLeads(isUS,suppressed,createdAt,phone)',
 'CREATE INDEX IF NOT EXISTS centralLeadStage ON centralLeads(stage,suppressed)',
 'CREATE INDEX IF NOT EXISTS centralLeadLease ON centralLeads(leaseOwner,leaseUntil)',
 'CREATE TABLE IF NOT EXISTS centralLeadMigrations (version TEXT PRIMARY KEY,completedAt TEXT DEFAULT CURRENT_TIMESTAMP)'
 ])await env.DB.prepare(sql).run();
 if(!await env.DB.prepare('SELECT version FROM centralLeadMigrations WHERE version=?').bind('importer-access-v1').first()){
 await env.DB.prepare("INSERT OR IGNORE INTO centralLeadAssignments(phone,agent,assignedBy) SELECT s.phone,lower(s.sourceEmail),lower(s.sourceEmail) FROM centralLeadSources s JOIN centralLeads l ON l.phone=s.phone JOIN adminAccounts a ON lower(a.email)=lower(s.sourceEmail) WHERE s.kind='agent' AND s.owner='agent:'||lower(s.sourceEmail) AND l.isUS=1 AND l.suppressed=0 AND a.isActive=1 AND a.status='approved' AND a.accountType IN ('agent','both')").run();
 await env.DB.prepare('INSERT OR IGNORE INTO centralLeadMigrations(version) VALUES(?)').bind('importer-access-v1').run();
 }
}
export async function storeCentralContacts(env,source,contacts){
 await leadSchema(env);
 for(let i=0;i<contacts.length;i+=15){const chunk=contacts.slice(i,i+15).filter(c=>/^\+\d{8,15}$/.test(c.phone));if(!chunk.length)continue;
 await env.DB.batch([
 env.DB.prepare('INSERT INTO centralLeads(phone,name,isUS) VALUES '+chunk.map(()=>'(?,?,?)').join(',')+" ON CONFLICT(phone) DO UPDATE SET name=CASE WHEN centralLeads.name=centralLeads.phone AND excluded.name<>excluded.phone THEN excluded.name ELSE centralLeads.name END").bind(...chunk.flatMap(c=>[c.phone,String(c.name||c.phone).slice(0,200),isUSPhone(c.phone)?1:0])),
 env.DB.prepare('INSERT INTO centralLeadSources(phone,owner,kind,sourceName,sourceEmail,groupsJson) VALUES '+chunk.map(()=>'(?,?,?,?,?,?)').join(',')+' ON CONFLICT(phone,owner) DO UPDATE SET sourceName=excluded.sourceName,sourceEmail=excluded.sourceEmail,groupsJson=(SELECT json_group_array(json(value)) FROM (SELECT value FROM json_each(centralLeadSources.groupsJson) UNION SELECT value FROM json_each(excluded.groupsJson)))').bind(...chunk.flatMap(c=>[c.phone,source.owner,source.kind,source.name||source.email,source.email,JSON.stringify(c.groups||[])]))
 ]);
 if(source.kind==='agent')await env.DB.prepare('INSERT OR IGNORE INTO centralLeadAssignments(phone,agent,assignedBy) SELECT phone,?,? FROM centralLeads WHERE isUS=1 AND suppressed=0 AND phone IN ('+chunk.map(()=>'?').join(',')+')').bind(source.email.toLowerCase(),source.email.toLowerCase(),...chunk.map(c=>c.phone)).run();
 }
}
export async function staffIdentity(request,env,auth,kind){
 if(kind==='affiliate'){const id=await auth.affiliate(request,env);if(!id)return null;const a=await env.DB.prepare('SELECT id,name,email,phone,status,isActive FROM affiliates WHERE id=?').bind(id).first();return a&&Number(a.isActive)&&a.status==='approved'?{...a,owner:'affiliate:'+id,kind}:null;}
 const email=await auth.email(request,env);if(!email)return null;const access=await auth.access(email,env),a=access.account;
 return a&&Number(a.isActive)&&a.status==='approved'&&['agent','both'].includes(a.accountType)?{...a,owner:'agent:'+email.toLowerCase(),kind:'agent'}:null;
}
async function existingAvatar(env,staff){if(staff.kind==='agent'&&await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='agentPublicProfiles'").first()){const p=await env.DB.prepare('SELECT photoUrl FROM agentPublicProfiles WHERE lower(agentEmail)=?').bind(staff.email.toLowerCase()).first();if(p?.photoUrl)return p.photoUrl;}return '/staff-avatar-1.svg';}
export async function configuredAccess(env,staff){
 let profile=await env.DB.prepare('SELECT * FROM staffOnboarding WHERE owner=?').bind(staff.owner).first();
 if(profile?.completed)return true;
 const shared=await sharedAgentImport(env,staff);
 const phone=profile?.phone||'+'+String(staff.phone||shared?.phone||'').replace(/\D/g,'');if(!/^\+\d{8,15}$/.test(phone))return false;
 if(!profile?.profileSaved){await env.DB.prepare('INSERT INTO staffOnboarding(owner,kind,phone,avatar,profileSaved) VALUES(?,?,?,?,1) ON CONFLICT(owner) DO UPDATE SET profileSaved=1,phone=excluded.phone').bind(staff.owner,staff.kind,phone,shared?.avatar||await existingAvatar(env,staff)).run();}
 const job=await env.DB.prepare('SELECT state FROM staffContactImports WHERE owner=?').bind(shared?.owner||staff.owner).first();let linked=!!shared||job?.state==='done';
 if(!linked&&staff.kind==='affiliate'&&await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='affiliateWhatsappImports'").first()){const old=await env.DB.prepare('SELECT state,total FROM affiliateWhatsappImports WHERE affiliateId=?').bind(staff.id).first();if(old?.state==='done'){linked=true;await env.DB.prepare("INSERT OR IGNORE INTO staffContactImports(owner,state,total) VALUES(?,'done',?)").bind(staff.owner,old.total).run();}}
 if(!linked){try{const r=await contactBridge(env,staff.kind==='affiliate'?'affiliate-'+staff.id+'@affinity-whatsapp.invalid':staff.email.toLowerCase(),'status');if(r.ok){const info=await r.json();linked=info.state==='ready';if(linked&&!job)await env.DB.prepare('INSERT OR IGNORE INTO staffContactImports(owner) VALUES(?)').bind(staff.owner).run();}}catch{}}
 if(linked)await env.DB.prepare('UPDATE staffOnboarding SET completed=1,updatedAt=CURRENT_TIMESTAMP WHERE owner=?').bind(staff.owner).run();return linked;
}
async function adminIdentity(request,env,auth){const email=await auth.email(request,env);if(!email)return null;const a=await auth.access(email,env);return a.isMaster||(a.account&&Number(a.account.isActive)&&a.account.status==='approved'&&['admin','both'].includes(a.account.accountType))?email.toLowerCase():null;}
async function inputJSON(request,url,max=600000){if(request.headers.get('origin')!==url.origin||!request.headers.get('content-type')?.startsWith('application/json'))throw Object.assign(Error('Solicitação inválida.'),{status:403});const s=await request.text();if(s.length>max)throw Object.assign(Error('Solicitação muito grande.'),{status:413});try{return JSON.parse(s)}catch{throw Object.assign(Error('Dados inválidos.'),{status:400})}}
export async function backfill(env){
 if(await env.DB.prepare('SELECT version FROM centralLeadMigrations WHERE version=?').bind('legacy-central-v1').first())return;
 // Legacy imports remain intact; central records are deduplicated and sources preserved.
 const exists=async name=>!!await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").bind(name).first();
 if(await exists('affiliateWhatsappLeads')){
 await env.DB.prepare("INSERT OR IGNORE INTO centralLeads(phone,name,isUS) SELECT phone,name,0 FROM affiliateWhatsappLeads").run();
 await env.DB.prepare("INSERT INTO centralLeadSources(phone,owner,kind,sourceName,sourceEmail,groupsJson) SELECT phone,'affiliate:'||affiliateId,'affiliate',affiliateName,affiliateEmail,groupsJson FROM affiliateWhatsappLeads WHERE 1 ON CONFLICT(phone,owner) DO UPDATE SET groupsJson=excluded.groupsJson").run();}
 if(await exists('whatsappLeads')){
 await env.DB.prepare('CREATE INDEX IF NOT EXISTS whatsappLeadPhoneStage ON whatsappLeads(phone,stage,updatedAt)').run();
 await env.DB.prepare("INSERT OR IGNORE INTO centralLeads(phone,name,isUS,stage,suppressed) SELECT phone,name,0,stage,CASE WHEN stage IN ('Recusada','Sem interesse','Já tem seguro') THEN 1 ELSE 0 END FROM whatsappLeads ORDER BY id").run();
 await env.DB.prepare("INSERT OR IGNORE INTO centralLeadSources(phone,owner,kind,sourceName,sourceEmail,groupsJson) SELECT l.phone,'agent:'||l.owner,'agent',coalesce(a.name,l.owner),l.owner,coalesce((SELECT json_group_array(json_object('id',g.groupId,'name',g.groupName)) FROM whatsappLeadGroups g WHERE g.owner=l.owner AND g.leadId=l.id),'[]') FROM whatsappLeads l LEFT JOIN adminAccounts a ON lower(a.email)=l.owner").run();
 await env.DB.prepare("UPDATE centralLeads SET suppressed=1,stage=(SELECT l.stage FROM whatsappLeads l WHERE l.phone=centralLeads.phone AND l.stage IN ('Recusada','Sem interesse','Já tem seguro') ORDER BY l.updatedAt DESC LIMIT 1) WHERE suppressed=0 AND EXISTS(SELECT 1 FROM whatsappLeads l WHERE l.phone=centralLeads.phone AND l.stage IN ('Recusada','Sem interesse','Já tem seguro'))").run();}
 // Conservative US classification: unknown/shared +1 prefixes remain admin-only.
 await env.DB.prepare("UPDATE centralLeads SET isUS=CASE WHEN length(phone)=12 AND substr(phone,1,2)='+1' AND substr(phone,6,1) BETWEEN '2' AND '9' AND substr(phone,3,3) IN ("+[...codes].map(c=>"'"+c+"'").join(',')+") THEN 1 ELSE 0 END").run();
 await env.DB.prepare('INSERT OR IGNORE INTO centralLeadMigrations(version) VALUES(?)').bind('legacy-central-v1').run();
}
export async function protectInternalContacts(env){
 const exists=async name=>!!await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").bind(name).first();
 const normalize=value=>{let digits=String(value||'').replace(/\D/g,'');if(digits.length===10)digits='1'+digits;return /^\d{8,15}$/.test(digits)?'+'+digits:null};
 const block=async(phones,stage)=>{const values=[...new Set(phones.map(normalize).filter(Boolean))];for(let i=0;i<values.length;i+=85){const c=values.slice(i,i+85);await env.DB.prepare('UPDATE centralLeads SET suppressed=1,stage=?,leaseOwner=NULL,leaseUntil=0 WHERE phone IN ('+c.map(()=>'?').join(',')+')').bind(stage,...c).run();}};
 if(await exists('crmClients')){const rows=await env.DB.prepare("SELECT phone,whatsapp,lower(trim(status)) AS status FROM crmClients WHERE lower(trim(status)) IN ('client','completed','active','agent')").all();await block(rows.results.filter(c=>c.status==='agent').flatMap(c=>[c.phone,c.whatsapp]),'Agente');await block(rows.results.filter(c=>c.status!=='agent').flatMap(c=>[c.phone,c.whatsapp]),'Cliente ativo');}
 if(await exists('agentPolicies')){const rows=await env.DB.prepare("SELECT p.clientPhone,c.phone,c.whatsapp FROM agentPolicies p LEFT JOIN crmClients c ON c.id=p.clientId WHERE lower(replace(replace(replace(trim(p.status),'_',''),'-',''),' ','')) IN ('active','ativa','ativo','inforce','issued')").all();await block(rows.results.flatMap(c=>[c.clientPhone,c.phone,c.whatsapp]),'Cliente ativo');}
 if(await exists('adminAccounts')){const staff=await env.DB.prepare("SELECT phone FROM adminAccounts WHERE isActive=1 AND status='approved' AND accountType IN ('agent','both')").all();await block(staff.results.map(c=>c.phone),'Agente');}
 if(!await env.DB.prepare('SELECT groupId FROM centralExcludedGroups LIMIT 1').first()&&!await env.DB.prepare("SELECT phone FROM centralLeads WHERE stage='Grupo excluído' LIMIT 1").first())return;
 await env.DB.prepare("UPDATE centralLeads SET suppressed=0,stage='Importados' WHERE stage='Grupo excluído' AND NOT EXISTS(SELECT 1 FROM centralLeadSources s,json_each(s.groupsJson) g JOIN centralExcludedGroups e ON e.groupId=json_extract(g.value,'$.id') WHERE s.phone=centralLeads.phone)").run();
 await env.DB.prepare("UPDATE centralLeads SET suppressed=1,stage='Grupo excluído',leaseOwner=NULL,leaseUntil=0 WHERE suppressed=0 AND EXISTS(SELECT 1 FROM centralLeadSources s,json_each(s.groupsJson) g JOIN centralExcludedGroups e ON e.groupId=json_extract(g.value,'$.id') WHERE s.phone=centralLeads.phone)").run();
}
async function decorate(env,rows){if(!rows.length)return [];const out=[];for(let i=0;i<rows.length;i+=90){const c=rows.slice(i,i+90),marks=c.map(()=>'?').join(','),phones=c.map(r=>r.phone);const [sources,assignments,history]=await Promise.all([env.DB.prepare('SELECT * FROM centralLeadSources WHERE phone IN ('+marks+')').bind(...phones).all(),env.DB.prepare('SELECT phone,agent FROM centralLeadAssignments WHERE phone IN ('+marks+')').bind(...phones).all(),env.DB.prepare('SELECT * FROM centralLeadOutcomes WHERE phone IN ('+marks+') ORDER BY id DESC').bind(...phones).all()]);out.push(...c.map(r=>({...r,sources:sources.results.filter(s=>s.phone===r.phone),assignments:assignments.results.filter(s=>s.phone===r.phone).map(s=>s.agent),history:history.results.filter(s=>s.phone===r.phone)})));}return out;}
function csvResponse(rows,filename){const cell=x=>'"'+String(x??'').replace(/^[=+@-]/,"'").replaceAll('"','""')+'"';return new Response('\ufeff'+rows.map(r=>r.map(cell).join(';')).join('\r\n'),{headers:{'content-type':'text/csv;charset=utf-8','content-disposition':'attachment; filename="'+filename+'"','cache-control':'no-store'}});}
export async function leadFlowRoute(request,env,auth){
 const url=new URL(request.url),path=url.pathname,admin=path==='/admin/central-leads'||path.startsWith('/api/admin/central-leads/'),kind=path.startsWith('/afiliados/')||path.startsWith('/api/affiliate/')?'affiliate':'agent';
 const onboard=['/afiliados/inicio','/agentes/inicio'].includes(path),queue=path==='/agentes/fila-leads',marketing=path==='/agentes/obrigacoes-marketing';
 if(!admin&&!onboard&&!queue&&!marketing&&!/^\/api\/(agent|affiliate)\/(onboarding|contact-import|lead-queue|marketing)\//.test(path))return null;
 try{
 const identity=admin?await adminIdentity(request,env,auth):await staffIdentity(request,env,auth,kind);if(!identity)return json({error:'Entre com uma conta aprovada para acessar.'},401);
 if(request.method==='GET'&&(onboard||queue||marketing||path==='/admin/central-leads'))return env.ASSETS.fetch(new Request(new URL(admin?'/central-leads-admin.html':marketing?'/marketing-obligations.html':queue?(url.searchParams.get('view')==='crm'?'/mobile-crm.html':'/central-leads-agent.html'):'/staff-onboarding.html',url),request));
 await leadSchema(env);const action=path.split('/').at(-1),input=request.method==='POST'?await inputJSON(request,url):{};
 if(!['GET','POST'].includes(request.method))return json({error:'Ação indisponível.'},405);
 if(admin){
 if(action==='list'&&request.method==='GET'){await backfill(env);await protectInternalContacts(env);const offset=Math.max(0,Number(url.searchParams.get('offset'))||0),category=url.searchParams.get('category')||'active';if(!['active','international',...terminal,'Grupo excluído','all'].includes(category))return json({error:'Categoria inválida.'},400);let where=category==='active'?'isUS=1 AND suppressed=0':category==='international'?'isUS=0':category==='all'?'1=1':'stage=? AND suppressed=1';if(category!=='Grupo excluído')where+=' AND '+visibleLeadSQL('centralLeads.phone');const args=(terminal.has(category)||category==='Grupo excluído')?[category]:[];const search=String(url.searchParams.get('search')||'').trim().slice(0,200),stage=url.searchParams.get('stage')||'';if(stage){if(!stages.includes(stage))return json({error:'Etapa inválida.'},400);where+=' AND stage=?';args.push(stage);}if(search){where+=' AND (name LIKE ? OR phone LIKE ? OR EXISTS(SELECT 1 FROM centralLeadSources s WHERE s.phone=centralLeads.phone AND (s.sourceName LIKE ? OR s.sourceEmail LIKE ? OR s.groupsJson LIKE ?)))';args.push(...Array(5).fill('%'+search+'%'));}const rows=await env.DB.prepare('SELECT * FROM centralLeads WHERE '+where+' ORDER BY createdAt DESC,phone LIMIT 100 OFFSET ?').bind(...args,offset).all(),total=await env.DB.prepare('SELECT count(*) AS count FROM centralLeads WHERE '+where).bind(...args).first(),agents=await env.DB.prepare("SELECT email,name FROM adminAccounts WHERE isActive=1 AND status='approved' AND accountType IN ('agent','both') ORDER BY name").all();return json({leads:await decorate(env,rows.results),total:total.count,agents:agents.results,stages});}
 if(action==='export'&&request.method==='GET'){await backfill(env);await protectInternalContacts(env);const category=url.searchParams.get('category')||'international';if(!['international','all'].includes(category))return json({error:'Categoria inválida.'},400);const rows=await env.DB.prepare('SELECT l.*,s.kind,s.sourceName,s.sourceEmail,s.groupsJson,s.priority FROM centralLeads l JOIN centralLeadSources s ON s.phone=l.phone '+'WHERE '+(category==='international'?'l.isUS=0 AND ':'')+visibleLeadSQL('l.phone')+' ORDER BY l.phone,s.owner').all();return csvResponse([['Nome','Telefone','Categoria','País','Tipo de fonte','Fonte','Email da fonte','Grupos','Prioridade'],...rows.results.map(l=>[l.name,l.phone,l.stage,l.isUS?'EUA':'Internacional / não confirmado',l.kind,l.sourceName,l.sourceEmail,JSON.parse(l.groupsJson).map(g=>g.name).join(' / '),l.priority?'Sim':'Não'])],'central-contatos-'+category+'.csv');}
 if(action==='exclude-groups'&&request.method==='POST'){const groups=input.groups;if(!Array.isArray(groups)||groups.length>100||groups.some(g=>!/^\d{5,25}(?:-\d{5,25})?@g\.us$/.test(g.id||'')||typeof g.excluded!=='boolean'))return json({error:'Selecione até 100 grupos válidos.'},400);await env.DB.batch(groups.map(g=>g.excluded?env.DB.prepare('INSERT INTO centralExcludedGroups(groupId,name,excludedBy) VALUES(?,?,?) ON CONFLICT(groupId) DO NOTHING').bind(g.id,String(g.name||g.id).slice(0,200),identity):env.DB.prepare('DELETE FROM centralExcludedGroups WHERE groupId=?').bind(g.id)));await protectInternalContacts(env);return json({ok:true,groups:groups.length});}
 if(action==='groups'&&request.method==='GET'){const rows=await env.DB.prepare("SELECT json_extract(g.value,'$.id') AS id,max(json_extract(g.value,'$.name')) AS name,count(DISTINCT s.phone) AS contacts,CASE WHEN e.groupId IS NULL THEN 0 ELSE 1 END AS excluded FROM centralLeadSources s,json_each(s.groupsJson) g LEFT JOIN centralExcludedGroups e ON e.groupId=json_extract(g.value,'$.id') GROUP BY json_extract(g.value,'$.id') ORDER BY name").all();return json({groups:rows.results});}
 if(action==='exclude-group'&&request.method==='POST'){if(!/^\d{5,25}(?:-\d{5,25})?@g\.us$/.test(input.groupId||''))return json({error:'Grupo inválido.'},400);if(input.excluded===false)await env.DB.prepare('DELETE FROM centralExcludedGroups WHERE groupId=?').bind(input.groupId).run();else await env.DB.prepare('INSERT INTO centralExcludedGroups(groupId,name,excludedBy) VALUES(?,?,?) ON CONFLICT(groupId) DO NOTHING').bind(input.groupId,String(input.name||input.groupId).slice(0,200),identity).run();await protectInternalContacts(env);return json({ok:true});}
 if(action==='classify'&&request.method==='POST'){const phones=[...new Set(Array.isArray(input.phones)?input.phones:[])];if(!phones.length||phones.length>100||!terminal.has(input.stage))return json({error:'Selecione contatos e uma categoria de encerramento.'},400);await env.DB.prepare('UPDATE centralLeads SET stage=?,suppressed=1,leaseOwner=NULL,leaseUntil=0 WHERE phone IN ('+phones.map(()=>'?').join(',')+')').bind(input.stage,...phones).run();return json({ok:true});}
 if(action==='assign'&&request.method==='POST'){
 await protectInternalContacts(env);
 const phones=[...new Set(Array.isArray(input.phones)?input.phones:[])],filtered=input.scope==='filtered';
 const count=input.count===undefined?phones.length:Number(input.count);
 if(!Number.isInteger(count)||count<1||count>1000||phones.length>100||(!filtered&&!phones.length))return json({error:'Informe uma quantidade entre 1 e 1.000 por agente e selecione contatos ou use os filtros.'},400);
 const available=await env.DB.prepare("SELECT lower(email) AS email FROM adminAccounts WHERE isActive=1 AND status='approved' AND accountType IN ('agent','both')").all(),allowed=new Set(available.results.map(a=>a.email)),agents=input.allAgents===true?[...allowed]:[...new Set(Array.isArray(input.agents)?input.agents.map(x=>String(x).toLowerCase()):[])];if(!agents.length||agents.some(a=>!allowed.has(a)))return json({error:'Escolha agentes aprovados.'},400);
 if(phones.some(p=>!isUSPhone(p)))return json({error:'Somente números dos EUA podem ser distribuídos.'},400);
 if(!filtered)for(const phone of phones){const l=await env.DB.prepare('SELECT suppressed,isUS FROM centralLeads WHERE phone=?').bind(phone).first();if(!l||l.suppressed||!l.isUS)return json({error:'A seleção contém um contato indisponível. Atualize a lista.'},409);}
 if(filtered&&!['active','all'].includes(input.category||'active'))return json({error:'Distribua apenas contatos disponíveis dos EUA.'},400);
 const results=[];
 for(const agent of agents){
  let where='l.suppressed=0 AND l.isUS=1 AND '+visibleLeadSQL('l.phone')+' AND NOT EXISTS(SELECT 1 FROM centralLeadAssignments a WHERE a.phone=l.phone AND a.agent=?)',args=[agent];
  if(!filtered){where+=' AND l.phone IN ('+phones.map(()=>'?').join(',')+')';args.push(...phones);}
  else {const search=String(input.search||'').trim().slice(0,200),stage=String(input.stage||'');if(stage){if(!stages.includes(stage))return json({error:'Etapa inválida.'},400);where+=' AND l.stage=?';args.push(stage);}if(search){where+=' AND (l.name LIKE ? OR l.phone LIKE ? OR EXISTS(SELECT 1 FROM centralLeadSources s WHERE s.phone=l.phone AND (s.sourceName LIKE ? OR s.sourceEmail LIKE ? OR s.groupsJson LIKE ?)))';args.push(...Array(5).fill('%'+search+'%'));}}
  // Interleave sources and groups before taking the batch, preserving a mixed queue.
  const candidates=await env.DB.prepare("WITH candidates AS (SELECT l.phone,l.createdAt,coalesce((SELECT min(s.owner||':'||coalesce(json_extract(s.groupsJson,'$[0].id'),'')) FROM centralLeadSources s WHERE s.phone=l.phone),'') AS bucket FROM centralLeads l WHERE "+where+"), ranked AS (SELECT phone,bucket,row_number() OVER(PARTITION BY bucket ORDER BY createdAt,phone) AS turn FROM candidates) SELECT phone FROM ranked ORDER BY turn,bucket,phone LIMIT ?").bind(...args,count).all();
  let assigned=0;
  for(let i=0;i<candidates.results.length;i+=20){const batch=await env.DB.batch(candidates.results.slice(i,i+20).map(({phone})=>env.DB.prepare('INSERT OR IGNORE INTO centralLeadAssignments(phone,agent,assignedBy) SELECT phone,?,? FROM centralLeads WHERE phone=? AND suppressed=0 AND isUS=1 AND '+visibleLeadSQL('centralLeads.phone')).bind(agent,identity,phone)));assigned+=batch.reduce((n,r)=>n+(r.meta?.changes||0),0);}
  results.push({agent,assigned});
 }
 return json({ok:true,requested:count,contacts:Math.max(0,...results.map(r=>r.assigned)),agents:agents.length,assignments:results.reduce((n,r)=>n+r.assigned,0),results});}
 return json({error:'Ação indisponível. A lista não permite exclusão.'},405);
 }
 const owner=identity.owner,email=identity.email.toLowerCase();
 if(path.includes('/marketing/')&&kind==='agent'){try{if(action==='list'&&request.method==='GET')return json({obligations:await listObligations(env,email)});if(action==='report-payment'&&request.method==='POST')return json(await reportPayment(env,input,email));return json({error:'Ação indisponível.'},405);}catch(e){return json({error:e.message},400);}}
 if(path.includes('/onboarding/')){
 const profile=await env.DB.prepare('SELECT * FROM staffOnboarding WHERE owner=?').bind(owner).first();
 if(action==='status'&&request.method==='GET'){const completed=await configuredAccess(env,identity),fresh=await env.DB.prepare('SELECT * FROM staffOnboarding WHERE owner=?').bind(owner).first(),account=await env.DB.prepare('SELECT passwordHash FROM '+(kind==='affiliate'?'affiliates':'adminAccounts')+' WHERE lower(email)=?').bind(email).first(),importIdentity=await staffImportIdentity(env,identity),job=await env.DB.prepare('SELECT state FROM staffContactImports WHERE owner=?').bind(importIdentity.owner).first();return json({kind,whatsappRequired:true,whatsappAllowed:true,name:identity.name,email,phone:fresh?.phone||identity.phone||'',avatar:fresh?.avatar||await existingAvatar(env,identity),profileSaved:!!fresh?.profileSaved,passwordSet:!!account?.passwordHash,completed,needsImport:completed&&job?.state!=='done',...(kind==='agent'?{...await registrationStatus(env,owner),...(await hasFeature(env,email,'five_rings')?await fiveRingsRequirement(env,email):{fiveRingsSyncDue:false,fiveRingsReminderDue:false})}:{})});}
 if(action==='theme'&&kind==='agent'&&['GET','POST'].includes(request.method)){try{return json(await agentAppearance(env,owner,request.method==='POST'?input:undefined));}catch(e){return json({error:e.message},400);}}
 if(action==='five-rings-postpone'&&request.method==='POST'&&kind==='agent')return json(await postponeFiveRings(env,email));
 if(action==='agent-number'&&request.method==='POST'&&kind==='agent'){try{await saveRegistration(env,owner,input);return json({ok:true});}catch(e){return json({error:e.message},400);}}
 if(action==='profile'&&request.method==='POST'){
 const phone='+'+String(input.phone||'').replace(/\D/g,'');if(!/^\+\d{8,15}$/.test(phone))return json({error:'Informe seu telefone com código do país.'},400);
 const savedAvatar=profile?.avatar||await existingAvatar(env,identity);let avatar=String(input.avatar||savedAvatar);if(avatar!==savedAvatar&&!/^\/staff-avatar-[1-6]\.svg$/.test(avatar)&&!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(avatar))return json({error:'Escolha um avatar ou uma foto JPEG, PNG ou WebP.'},400);if(avatar.length>500000)return json({error:'Reduza a foto para até 350 KB.'},400);
 const table=kind==='affiliate'?'affiliates':'adminAccounts',existing=await env.DB.prepare('SELECT passwordHash FROM '+table+' WHERE lower(email)=?').bind(email).first();
 if(input.password&&(String(input.password).length<10||String(input.password).length>72))return json({error:'Use uma senha de 10 a 72 caracteres.'},400);
 if(input.password&&existing?.passwordHash&&!await auth.compare(String(input.currentPassword||''),existing.passwordHash))return json({error:'Confira sua senha atual.'},400);
 if(!existing?.passwordHash&&!input.password)return json({error:'Crie uma senha para seu acesso.'},400);
 if(kind==='agent'&&(input.agentNumber!==undefined||input.numberPending!==undefined)){try{await saveRegistration(env,owner,input);}catch(e){return json({error:e.message},400);}}
 const hash=input.password?await auth.hash(input.password,12):existing.passwordHash;await env.DB.batch([env.DB.prepare('UPDATE '+table+' SET phone=?,passwordHash=?,updatedAt=CURRENT_TIMESTAMP WHERE lower(email)=?').bind(phone,hash,email),env.DB.prepare('INSERT INTO staffOnboarding(owner,kind,phone,avatar,profileSaved) VALUES(?,?,?,?,1) ON CONFLICT(owner) DO UPDATE SET phone=excluded.phone,avatar=excluded.avatar,profileSaved=1,updatedAt=CURRENT_TIMESTAMP').bind(owner,kind,phone,avatar)]);return json({ok:true});}
 if(action==='finish'&&request.method==='POST'){const importIdentity=await staffImportIdentity(env,identity),imported=await env.DB.prepare('SELECT state FROM staffContactImports WHERE owner=?').bind(importIdentity.owner).first();if(!profile?.profileSaved||imported?.state!=='done')return json({error:'Preencha seu perfil e conclua a importação primeiro.'},409);await env.DB.prepare('UPDATE staffOnboarding SET completed=1,updatedAt=CURRENT_TIMESTAMP WHERE owner=?').bind(owner).run();return json({ok:true});}
 }
 if(path.includes('/contact-import/')){
 const importIdentity=await staffImportIdentity(env,identity),owner=importIdentity.owner,bridgeOwner=importIdentity.bridgeOwner;
 let job=await env.DB.prepare('SELECT * FROM staffContactImports WHERE owner=?').bind(owner).first();
 if(action==='connect'&&request.method==='POST'){if(input.consent!==true)return json({error:'Confirme a importação de todos os contatos disponíveis para os Admins.'},400);const profile=await env.DB.prepare('SELECT profileSaved FROM staffOnboarding WHERE owner=?').bind(owner).first();if(!profile?.profileSaved)return json({error:'Preencha o perfil primeiro.'},409);const r=await contactBridge(env,bridgeOwner,'connect','POST');if(!r.ok)return r;await env.DB.prepare("INSERT INTO staffContactImports(owner) VALUES(?) ON CONFLICT(owner) DO UPDATE SET cursor=0,total=0,state='connecting',consentedAt=CURRENT_TIMESTAMP").bind(owner).run();return json({ok:true});}
 if(action==='status'&&request.method==='GET'){if(job?.state==='done')return json({state:'done',count:job.total});return job?contactBridge(env,bridgeOwner,'status'):json({state:'disconnected'});}
 if(action==='sync'&&request.method==='POST'){
 if(!job)return json({error:'Conecte o WhatsApp primeiro.'},409);if(job.state==='done')return json({state:'done',count:job.total});
 const r=await contactBridge(env,bridgeOwner,'all-contacts');if(!r.ok)return r;const data=await r.json();if(data.pending)return json({...data,state:'reading'},202);
 const contacts=data.contacts.filter(c=>/^\+\d{8,15}$/.test(c.phone)),end=Math.min(job.cursor+150,contacts.length);await storeCentralContacts(env,{owner,kind:importIdentity.kind,name:importIdentity.name,email:importIdentity.email},contacts.slice(job.cursor,end));await env.DB.prepare('UPDATE staffContactImports SET cursor=?,total=?,state=? WHERE owner=?').bind(end,contacts.length,end===contacts.length?'done':'importing',owner).run();
 if(end===contacts.length&&importIdentity.kind==='affiliate')try{await contactBridge(env,bridgeOwner,'disconnect','POST')}catch{}
 return json({state:end===contacts.length?'done':'importing',imported:end,total:contacts.length,count:contacts.length,unresolved:data.unresolved||0},end===contacts.length?200:202);}
 if(action==='export')return json({error:'Exportação exclusiva dos administradores.'},403);
 if(action==='groups'&&request.method==='GET'){const rows=await env.DB.prepare("SELECT json_extract(g.value,'$.id') AS id,max(json_extract(g.value,'$.name')) AS name,count(DISTINCT s.phone) AS contacts,EXISTS(SELECT 1 FROM centralAgentExcludedGroups e WHERE e.owner=s.owner AND e.groupId=json_extract(g.value,'$.id')) AS excluded FROM centralLeadSources s,json_each(s.groupsJson) g WHERE s.owner=? AND NOT EXISTS(SELECT 1 FROM centralExcludedGroups blocked WHERE blocked.groupId=json_extract(g.value,'$.id')) GROUP BY json_extract(g.value,'$.id') ORDER BY name").bind(owner).all();return json({groups:rows.results});}
 if(action==='exclude-group'&&request.method==='POST'){if(kind!=='agent')return json({error:'Disponível para agentes.'},403);const group=String(input.groupId||'');if(!/^\d{5,25}(?:-\d{5,25})?@g\.us$/.test(group))return json({error:'Grupo inválido.'},400);const exists=await env.DB.prepare("SELECT 1 FROM centralLeadSources s,json_each(s.groupsJson) g WHERE s.owner=? AND json_extract(g.value,'$.id')=? LIMIT 1").bind(owner,group).first();if(!exists)return json({error:'Grupo não disponível nesta conta.'},404);if(input.excluded===false)await env.DB.prepare('DELETE FROM centralAgentExcludedGroups WHERE owner=? AND groupId=?').bind(owner,group).run();else await env.DB.prepare('INSERT OR IGNORE INTO centralAgentExcludedGroups(owner,groupId) VALUES(?,?)').bind(owner,group).run();await env.DB.prepare("UPDATE centralLeads SET leaseOwner=NULL,leaseUntil=0 WHERE leaseOwner=? AND EXISTS(SELECT 1 FROM centralLeadSources s,json_each(s.groupsJson) g JOIN centralAgentExcludedGroups e ON e.owner=s.owner AND e.groupId=json_extract(g.value,'$.id') WHERE s.phone=centralLeads.phone AND s.owner=?)").bind(email,owner).run();return json({ok:true});}
 if(action==='contacts'&&request.method==='GET'){await protectInternalContacts(env);const offset=Math.max(0,Number(url.searchParams.get('offset'))||0),group=url.searchParams.get('group')||'',where="s.owner=? AND "+visibleLeadSQL('s.phone')+(group?" AND EXISTS(SELECT 1 FROM json_each(s.groupsJson) g WHERE json_extract(g.value,'$.id')=?)":""),args=group?[owner,group]:[owner];const rows=await env.DB.prepare('SELECT l.phone,l.name,s.priority FROM centralLeads l JOIN centralLeadSources s ON s.phone=l.phone WHERE '+where+' ORDER BY l.name,l.phone LIMIT 100 OFFSET ?').bind(...args,offset).all(),total=await env.DB.prepare('SELECT count(*) AS count FROM centralLeadSources s WHERE '+where).bind(...args).first();return json({contacts:rows.results,total:total.count});}
 if(action==='priority'&&request.method==='POST'){const phones=[...new Set(Array.isArray(input.phones)?input.phones:[])];if(!phones.length||phones.length>100)return json({error:'Selecione até 100 contatos.'},400);for(let i=0;i<phones.length;i+=90){const chunk=phones.slice(i,i+90);await env.DB.prepare('UPDATE centralLeadSources SET priority=? WHERE owner=? AND phone IN ('+chunk.map(()=>'?').join(',')+')').bind(input.priority===false?0:1,owner,...chunk).run();}return json({ok:true});}
 }
 if(path.includes('/lead-queue/')&&kind==='agent'){
 const profile=await env.DB.prepare('SELECT completed FROM staffOnboarding WHERE owner=?').bind(owner).first();if(!profile?.completed&&!await configuredAccess(env,identity))return json({error:'Conclua a configuração inicial.',onboarding:'/agentes/inicio'},409);
 await protectInternalContacts(env);
 const now=Date.now();
 if(action==='next'&&request.method==='POST'){
 await env.DB.prepare("UPDATE centralLeads SET leaseOwner=NULL,leaseUntil=0 WHERE leaseOwner=? AND EXISTS(SELECT 1 FROM centralLeadSources s,json_each(s.groupsJson) g JOIN centralAgentExcludedGroups e ON e.owner=s.owner AND e.groupId=json_extract(g.value,'$.id') WHERE s.phone=centralLeads.phone AND s.owner=?)").bind(email,owner).run();
 let lead=await env.DB.prepare('SELECT * FROM centralLeads WHERE leaseOwner=? AND leaseUntil>? AND suppressed=0 AND isUS=1 LIMIT 1').bind(email,now).first();
 if(!lead){const stage=String(input.stage||'');if(stage&&!stages.includes(stage))return json({error:'Etapa inválida.'},400);await reserveFairLead(env,email,owner,stage,now);lead=await env.DB.prepare('SELECT * FROM centralLeads WHERE leaseOwner=? AND leaseUntil>? AND suppressed=0 AND isUS=1 LIMIT 1').bind(email,now).first();}
 return json({lead:lead?(await decorate(env,[lead]))[0]:null,stages,leaseMinutes:30});}
 if(action==='result'&&request.method==='POST'){
 const phone=String(input.phone||''),stage=String(input.stage||''),response=String(input.response||''),attempts=Number(input.attempts),note=String(input.note||'').trim(),appointment=String(input.appointment||'');if(!stages.includes(stage)||!['Respondeu','Sem resposta','Reunião marcada'].includes(response)||!Number.isInteger(attempts)||attempts<1||attempts>100||!note||note.length>2000)return json({error:'Preencha resultado, tentativas, etapa e observação.'},400);if((appointment||stage==='Reunião agendada'||response==='Reunião marcada')&&(!appointment||!Number.isFinite(Date.parse(appointment))||Date.parse(appointment)<=now))return json({error:'Informe uma data futura para a reunião.'},400);
 const lead=await env.DB.prepare('SELECT * FROM centralLeads WHERE phone=? AND leaseOwner=? AND leaseUntil>? AND suppressed=0 AND isUS=1').bind(phone,email,now).first();if(!lead)return json({error:'Este lead não está disponível. Atualize a fila.'},409);
 const next=appointment?Date.parse(appointment):now+86400000,storedStage=stage==='Emitida'?'Cliente ativo':stage;
 let sale=null,reference=null;if(stage==='Emitida'){try{if(!input.sale?.category)throw Error('Selecione a categoria do plano fechado.');sale=classifySale(input.sale);}catch(error){return json({error:error.message},400);}await ratesSchema(env);reference=await env.DB.prepare('SELECT payoutCents FROM affiliateReferenceRates WHERE bandKey=?').bind(sale.band.key).first();}
 const statements=[
 env.DB.prepare('INSERT INTO centralLeadOutcomes(phone,agent,response,attempts,stage,note,appointment) SELECT phone,?,?,?,?,?,? FROM centralLeads WHERE phone=? AND leaseOwner=? AND leaseUntil>? AND suppressed=0').bind(email,response,attempts,stage,note,appointment||null,phone,email,now),
 env.DB.prepare('UPDATE centralLeadAssignments SET nextAt=? WHERE phone=? AND EXISTS(SELECT 1 FROM centralLeads WHERE phone=? AND leaseOwner=? AND leaseUntil>? AND suppressed=0)').bind(next,phone,phone,email,now),
 env.DB.prepare('UPDATE centralLeads SET stage=?,suppressed=?,leaseOwner=NULL,leaseUntil=0,updatedAt=CURRENT_TIMESTAMP WHERE phone=? AND leaseOwner=? AND leaseUntil>? AND suppressed=0').bind(storedStage,terminal.has(storedStage)?1:0,phone,email,now)
 ];if(sale)statements.splice(2,0,env.DB.prepare('INSERT INTO centralLeadClosures(phone,agent,product,monthlyPremiumCents,bandKey,referencePayoutCents) SELECT phone,?,?,?,?,? FROM centralLeads WHERE phone=? AND leaseOwner=? AND leaseUntil>? AND suppressed=0 ON CONFLICT(phone) DO UPDATE SET agent=excluded.agent,product=excluded.product,monthlyPremiumCents=excluded.monthlyPremiumCents,bandKey=excluded.bandKey,referencePayoutCents=excluded.referencePayoutCents,confirmedAt=CURRENT_TIMESTAMP').bind(email,sale.band.product,sale.cents,sale.band.key,reference?.payoutCents??null,phone,email,now));if(sale)statements.splice(3,0,env.DB.prepare("INSERT OR IGNORE INTO marketingObligations(phone,payer,annualPremiumCents) SELECT phone,?,? FROM centralLeads WHERE phone=? AND leaseOwner=? AND leaseUntil>? AND suppressed=0 AND CURRENT_TIMESTAMP>='2026-10-09 04:00:00' AND EXISTS(SELECT 1 FROM centralLeadSources s WHERE s.phone=centralLeads.phone AND (s.kind='affiliate' OR (s.kind='agent' AND lower(s.sourceEmail)<>centralLeads.leaseOwner)))").bind(email,sale.cents*12,phone,email,now));const results=await env.DB.batch(statements);return results[0].meta?.changes?json({ok:true,suppressed:terminal.has(storedStage)}):json({error:'O lead foi atualizado por outro usuário.'},409);}
 }
 return json({error:'Ação indisponível.'},405);
 }catch(e){console.error('lead_flow_failure',e?.name||'Error');return json({error:e.status?e.message:'Não foi possível concluir agora. Tente novamente.'},e.status||503);}
}

export async function registrationStatus(env,owner,now=Date.now()) {await env.DB.prepare('CREATE TABLE IF NOT EXISTS agentNumberDefaults(key TEXT PRIMARY KEY,number TEXT NOT NULL,updatedBy TEXT,updatedAt TEXT DEFAULT CURRENT_TIMESTAMP)').run();const row=await env.DB.prepare('SELECT * FROM agentRegistrationNumbers WHERE owner=?').bind(owner).first();return {agentNumber:row?.number||'',numberPending:row?!!row.pending:true,numberReminderDue:!row||(!!row.pending&&Number(row.nextPromptAt)<=now),effectiveAgentNumber:row&&!row.pending?row.number:(await env.DB.prepare("SELECT number FROM agentNumberDefaults WHERE key='rafael'").first())?.number||'',usingAdminNumber:!row||!!row.pending};}
export async function saveRegistration(env,owner,input,now=Date.now()) {const existing=await env.DB.prepare('SELECT number,pending FROM agentRegistrationNumbers WHERE owner=?').bind(owner).first();const number=String(input.agentNumber||'').trim();const pending=input.numberPending===true;if(existing&&!existing.pending){if(!pending&&number===existing.number)return;throw Error('Seu número de agente já foi cadastrado e não pode ser alterado.');}if(!pending&&!/^[A-Za-z0-9][A-Za-z0-9 ._-]{0,59}$/.test(number))throw Error('Informe seu número de agente ou marque como pendente.');await env.DB.prepare('INSERT INTO agentRegistrationNumbers(owner,number,pending,nextPromptAt) VALUES(?,?,?,?) ON CONFLICT(owner) DO UPDATE SET number=excluded.number,pending=excluded.pending,nextPromptAt=excluded.nextPromptAt,updatedAt=CURRENT_TIMESTAMP WHERE agentRegistrationNumbers.pending=1').bind(owner,pending?null:number,pending?1:0,pending?now+15*86400000:0).run();}

export function visibleLeadSQL(phone){return "NOT EXISTS(SELECT 1 FROM centralLeadSources excludedSource,json_each(excludedSource.groupsJson) excludedGroup JOIN centralExcludedGroups blocked ON blocked.groupId=json_extract(excludedGroup.value,'$.id') WHERE excludedSource.phone="+phone+")";}
