import { useState } from 'react';
import AdminSidebar from '@/components/AdminSidebar';
import { trpc } from '@/lib/trpc';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';

export default function AdminAffiliateLeads() {
  const query = trpc.admin.listAffiliateLeads.useQuery(); const update = trpc.admin.updateAffiliateLead.useMutation(); const [editing, setEditing] = useState<number | null>(null); const [value, setValue] = useState('0'); const [status, setStatus] = useState<'pending'|'converted'|'closed'>('pending');
  return <div className="min-h-screen bg-black text-white lg:pl-64"><AdminSidebar /><main className="mx-auto max-w-6xl space-y-6 px-4 py-8"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-gold">Afiliados</p><h1 className="mt-2 text-3xl font-bold">Leads e pagamentos</h1><p className="mt-2 text-gray-400">Aprove a conversão e defina individualmente quanto será pago por cada lead.</p></div><div className="space-y-3">{(query.data || []).map(lead => <Card key={lead.id} className="border-gold/20 bg-[#0b1524] p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-lg font-bold">{lead.visitorName}</p><p className="text-sm text-gray-400">{lead.visitorEmail} · {lead.visitorPhone}</p>{lead.notes && <p className="mt-3 whitespace-pre-line rounded-lg bg-black/30 p-3 text-sm text-gray-300">{lead.notes}</p>}<p className="mt-2 text-xs text-gold">Afiliado #{lead.affiliateId} · {lead.status === 'converted' ? 'Convertido' : lead.status === 'closed' ? 'Encerrado' : 'Pendente'} · Valor: ${Number(lead.commissionAmount || 0).toFixed(2)}</p></div><Button variant="outline" onClick={() => { setEditing(lead.id); setStatus(lead.status); setValue(String(lead.commissionAmount || 0)); }}>Definir resultado e valor</Button></div>{editing === lead.id && <div className="mt-4 grid gap-3 border-t border-white/10 pt-4 sm:grid-cols-3"><select className="h-10 rounded-md border border-white/20 bg-black px-3" value={status} onChange={e => setStatus(e.target.value as typeof status)}><option value="pending">Pendente</option><option value="converted">Convertido</option><option value="closed">Não convertido</option></select><Input type="number" min="0" step="0.01" placeholder="Valor a pagar" value={value} onChange={e => setValue(e.target.value)} /><Button className="bg-gold text-black" onClick={async () => { try { await update.mutateAsync({ id: lead.id, status, commissionAmount: Number(value), notes: lead.notes || '' }); setEditing(null); await query.refetch(); toast.success('Lead atualizado'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Erro'); } }}>Salvar</Button></div>}</Card>)}</div></main></div>;
}
