// Browser QA uses an isolated bridge/database, never a real WhatsApp send.
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import http from 'node:http';import {Readable} from 'node:stream';import {spawn} from 'node:child_process';import {createHmac,createHash} from 'node:crypto';import {DatabaseSync} from 'node:sqlite';import assert from 'node:assert/strict';import puppeteer from 'puppeteer';
import worker from '../../recovered-live/worker/affinity-agent-whatsapp-portal.js';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'affinity-media-browser-')),downloads=path.join(root,'downloads');fs.mkdirSync(downloads);
const secret='synthetic-browser-test-secret-32-characters',owner='browser@example.test',chat='15555550100@c.us';let child,browser,server;
const digest=b=>createHash('sha256').update(b).digest('hex');
const fixtures=[];
const wav=()=>{const count=16000,b=Buffer.alloc(44+count*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVE',8);b.write('fmt ',12);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(16000,24);b.writeUInt32LE(32000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(count*2,40);for(let n=0;n<count;n++)b.writeInt16LE(Math.round(1000*Math.sin(n*440*2*Math.PI/16000)),44+n*2);return b;};
const pdf=()=>{const stream='BT /F1 16 Tf 30 60 Td (Affinity PDF test) Tj ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 240 100] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];let s='%PDF-1.4\n',offsets=[0];objects.forEach((x,i)=>{offsets.push(Buffer.byteLength(s));s+=`${i+1} 0 obj\n${x}\nendobj\n`;});const pos=Buffer.byteLength(s);s+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(x=>String(x).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+pos+'\n%%EOF\n';return Buffer.from(s);};
fixtures.push({id:'png',mime:'image/png',kind:'image',name:'imagem.png',bytes:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jf3cAAAAASUVORK5CYII=','base64')},{id:'wav',mime:'audio/wav',kind:'audio',name:'audio.wav',bytes:wav()},{id:'pdf',mime:'application/pdf',kind:'document',name:'documento.pdf',bytes:pdf()},{id:'mp4',mime:'video/mp4',kind:'video',name:'video.mp4',bytes:fs.readFileSync(new URL('../../recovered-live/public/media/Video1_fc21905a.mp4',import.meta.url))});
if(process.env.WHATSAPP_TEST_LIVE_DATA_DIR){const db=new DatabaseSync(path.join(process.env.WHATSAPP_TEST_LIVE_DATA_DIR,'history.sqlite'),{readOnly:true});const row=db.prepare("SELECT mediaKey,mime FROM messages WHERE mediaKind='audio' AND mediaState='ready' AND mime LIKE 'audio/ogg%' LIMIT 1").get();db.close();if(row)fixtures.push({id:'ogg',mime:row.mime,kind:'audio',name:'voz.ogg',bytes:fs.readFileSync(path.join(process.env.WHATSAPP_TEST_LIVE_DATA_DIR,'media',row.mediaKey))});}
try{
child=spawn(process.execPath,[path.join(import.meta.dirname,'server.mjs')],{env:{...process.env,WHATSAPP_BRIDGE_SECRET:secret,WHATSAPP_DATA_DIR:root,WHATSAPP_SEND_ENABLED:'false',HOST:'127.0.0.1',PORT:'0'},stdio:['ignore','pipe','pipe']});
const port=await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('Bridge startup timeout')),15000);child.once('error',reject);child.stdout.on('data',b=>{out+=b;for(const line of out.split('\n'))try{const v=JSON.parse(line);if(v.port){clearTimeout(timer);resolve(v.port);}}catch{}});});
const db=new DatabaseSync(path.join(root,'history.sqlite'));for(const f of fixtures){const key=digest(f.bytes);fs.writeFileSync(path.join(root,'media',key),f.bytes,{mode:0o600});db.prepare('INSERT INTO messages(owner,id,chat,body,direction,stamp,mediaKey,mime,filename,mediaKind,mediaSize,mediaState) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(owner,f.id,chat,'','received',1700000000,key,f.mime,f.name,f.kind,f.bytes.length,'ready');}db.close();
const ticket=()=>{const p=Buffer.from(JSON.stringify({aud:'affinity-whatsapp',owner,exp:Math.floor(Date.now()/1000)+60})).toString('base64url');return p+'.'+createHmac('sha256',secret).update(p).digest('base64url');};
const items=[{id:'emoji',mediaKind:'file',body:'Olá 👨‍👩‍👧‍👦 👍🏽 🇧🇷 ❤️ 😀 <script>test</script>',direction:'received',stamp:1700000000},...fixtures.map(f=>({id:f.id,body:'',direction:'received',stamp:1700000001,mediaKind:f.kind,mime:f.mime,filename:f.name,mediaState:'ready',mediaUrl:'/api/agent/whatsapp/media?id='+f.id}))];
server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/agentes/whatsapp'){const response=await worker.fetch(new Request('http://localhost/agentes/whatsapp'),{PORTAL:{fetch:async()=>Response.json({state:'ready'})}});res.writeHead(200,{'content-type':'text/html'});return res.end(await response.text());}const action=url.pathname.split('/').at(-1);if(action==='media'||action==='send'){const response=await fetch('http://127.0.0.1:'+port+'/'+action+url.search,{method:req.method,headers:{authorization:'Bearer '+ticket(),...(req.headers.range?{range:req.headers.range}:{})},...(req.method==='POST'?{body:'{}'}:{})});res.writeHead(response.status,Object.fromEntries(response.headers));return Readable.fromWeb(response.body).pipe(res);}let data=action==='status'?{state:'ready'}:action==='chats'?[{chat}]:action==='messages'?items:[];res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(data));}catch{res.writeHead(500);res.end('Test server failure');}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;
browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required','--mute-audio','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});const page=await browser.newPage();await page.setViewport({width:1280,height:900});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/agentes/whatsapp');await page.waitForSelector('#chats button');await page.click('#chats button');await page.waitForSelector('#messages video');
await page.waitForFunction(()=>[...document.querySelectorAll('#messages img')].every(x=>x.complete&&x.naturalWidth>0));
await page.waitForFunction(()=>[...document.querySelectorAll('#messages audio,#messages video')].every(x=>x.readyState>=2),{timeout:45000});
const playback=await page.evaluate(async()=>{const results=[];for(const media of document.querySelectorAll('#messages audio,#messages video')){await media.play();await new Promise(resolve=>setTimeout(resolve,1200));results.push({type:media.tagName,advanced:media.currentTime>0,currentTime:media.currentTime,duration:media.duration,paused:media.paused,ready:media.readyState,error:media.error?.code||null});media.pause();}return results;});assert(playback.every(x=>x.advanced&&!x.error),JSON.stringify(playback));console.log('PASS: PNG decoded; WAV, MP4'+(fixtures.some(x=>x.id==='ogg')?', existing Ogg voice':'')+' decoded and playback advanced.');
assert.equal(await page.$eval('[data-message-id="emoji"] .message-body',x=>x.textContent),items[0].body);assert.equal(await page.$eval('[data-message-id="emoji"]',x=>x.querySelectorAll('script').length),0);assert.equal(await page.$eval('[data-message-id="emoji"]',x=>x.querySelectorAll('.document').length),0);console.log('PASS: Unicode emojis, literal markup and plain text without false attachment warnings.');
const cdp=await page.createCDPSession();await cdp.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});
for(const f of fixtures){await page.click('[data-message-id="'+f.id+'"] a[download]');const target=path.join(downloads,f.name);for(let n=0;n<100&&!fs.existsSync(target);n++)await new Promise(resolve=>setTimeout(resolve,100));assert(fs.existsSync(target),'Download missing: '+f.id);assert.equal(digest(fs.readFileSync(target)),digest(f.bytes),'Download integrity: '+f.id);}
console.log('PASS: image, audio, video and PDF downloaded with exact SHA-256 and filenames.');
for(const f of fixtures){const r=await fetch(base+'/api/agent/whatsapp/media?id='+f.id,{headers:{range:'bytes=-16'}});assert.equal(r.status,206);assert.deepEqual(Buffer.from(await r.arrayBuffer()),f.bytes.subarray(-16));}console.log('PASS: suffix ranges for audio/video seeking.');
for(const f of fixtures){const target=path.join(root,f.name);fs.writeFileSync(target,f.bytes);const input=await page.$('#mediaImage');if(f.bytes.length<=8000000){await input.uploadFile(target);await page.waitForFunction(name=>document.querySelector('#mediaLabel').textContent===name||document.querySelector('#mediaLabel').textContent==='Mensagem de voz pronta',{},f.name);await page.click('#clearMedia');}}
const videoBytes=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=64;c.height=64;const stream=c.captureStream(10),rec=new MediaRecorder(stream,{mimeType:'video/webm'}),chunks=[];const stopped=new Promise(resolve=>rec.onstop=resolve);rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.start();const ctx=c.getContext('2d');for(let n=0;n<5;n++){ctx.fillStyle=n%2?'red':'blue';ctx.fillRect(0,0,64,64);await new Promise(r=>setTimeout(r,100));}rec.stop();await stopped;stream.getTracks().forEach(t=>t.stop());return [...new Uint8Array(await new Blob(chunks,{type:'video/webm'}).arrayBuffer())];});const smallVideo=path.join(root,'synthetic.webm');fs.writeFileSync(smallVideo,Buffer.from(videoBytes));await(await page.$('#mediaImage')).uploadFile(smallVideo);await page.waitForFunction(()=>document.querySelector('#mediaLabel').textContent==='synthetic.webm');await page.click('#clearMedia');console.log('PASS: selecting a generated playable WebM video.');
await page.click('#recordVoice');await page.waitForFunction(()=>document.querySelector('#recordVoice').textContent==='Parar gravação');await new Promise(resolve=>setTimeout(resolve,700));await page.click('#recordVoice');await page.waitForFunction(()=>!document.querySelector('#voicePreview').hidden);assert(await page.$eval('#voicePreview',x=>x.src.startsWith('blob:')));await page.click('#clearMedia');console.log('PASS: attachment selection and voice recording with synthetic microphone.');
await page.type('#text','Teste local 😀');await page.click('#send');await page.waitForFunction(()=>document.querySelector('#sendError').textContent.includes('Envios bloqueados'));console.log('PASS: send blocked against isolated real bridge; no WhatsApp session or delivery.');assert.deepEqual(errors,[]);
if(process.env.WHATSAPP_QA_SCREENSHOT)await page.screenshot({path:process.env.WHATSAPP_QA_SCREENSHOT,fullPage:true});
console.log('All browser media checks passed.');
}finally{await browser?.close();await new Promise(resolve=>server?server.close(resolve):resolve());if(child&&child.exitCode===null){await new Promise(resolve=>{child.once('exit',resolve);child.kill('SIGTERM');});}fs.rmSync(root,{recursive:true,force:true});}
