import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {affiliateWhatsappRoute} from './worker/affiliate-whatsapp.js';
test('affiliate QR import is consented, attributed, permanent and isolated from other affiliates',async()=>{
 const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE adminAccounts(email TEXT,name TEXT,phone TEXT,isActive INTEGER,status TEXT,accountType TEXT)");db.exec('CREATE TABLE affiliates(id INTEGER PRIMARY KEY,name TEXT,email TEXT,isActive INTEGER,status TEXT);');db.prepare('INSERT INTO affiliates VALUES(?,?,?,?,?)').run(1,'Afiliado A','a@example.test',1,'approved');db.prepare('INSERT INTO affiliates VALUES(?,?,?,?,?)').run(2,'Afiliado B','b@example.test',1,'approved');
 const prepare=sql=>{let args=[];return {bind(...v){args=v;return this},async first(){return db.prepare(sql).get(...args)},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}}}};
 const env={DB:{prepare,batch:async xs=>Promise.all(xs.map(x=>x.run()))},WHATSAPP_BRIDGE_URL:'https://bridge.example.test',WHATSAPP_BRIDGE_SECRET:'a'.repeat(48)},auth={affiliate:async r=>Number(r.headers.get('x-affiliate'))||null,email:async r=>r.headers.get('x-admin'),access:async()=>({account:{accountType:'admin',isActive:1,status:'approved'}})};
 const original=globalThis.fetch;let pending=true;globalThis.fetch=async(url,options)=>{assert.equal(options.redirect,'manual');const action=new URL(url).pathname;if(action==='/connect'||action==='/disconnect')return Response.json({ok:true});if(action==='/status')return Response.json({state:'ready'});if(action==='/all-contacts'){if(pending){pending=false;return Response.json({pending:true,group:1,totalGroups:2},{status:202})}return Response.json({contacts:[{name:'Pessoa',phone:'+15555550100',groups:[{id:'123456789@g.us',name:'Grupo'}]}],unresolved:1});}throw Error('Unexpected bridge action');};
 const call=(action,input,id=1,method)=>affiliateWhatsappRoute(new Request('https://www.affinityfc.org/api/affiliate/whatsapp/'+action,{method:method||(input?'POST':'GET'),headers:{'x-affiliate':String(id),...(input?{'content-type':'application/json',origin:'https://www.affinityfc.org'}:{})},...(input?{body:JSON.stringify(input)}:{})}),env,auth);
 try{
  assert.equal((await call('connect',{consent:false})).status,400);assert.equal((await call('connect',{consent:true})).status,200);
  assert.equal((await(await call('sync',{})).json()).pending,true);const done=await(await call('sync',{})).json();assert.equal(done.state,'done');assert.equal(done.count,1);
  const lead=db.prepare('SELECT * FROM affiliateWhatsappLeads').get();assert.equal(lead.affiliateId,1);assert.equal(lead.affiliateName,'Afiliado A');assert.equal(lead.source,'whatsapp_affiliate');
  assert.equal((await call('delete',{})).status,405);assert.equal((await call('leads',null,1,'DELETE')).status,405);
  assert.equal((await call('export',null,2)).status,403);assert.equal((await call('export')).status,403);
  const adminUrl='https://www.affinityfc.org/api/admin/affiliate-whatsapp/leads';assert.equal((await affiliateWhatsappRoute(new Request(adminUrl),env,auth)).status,401);
  const admin=await(await affiliateWhatsappRoute(new Request(adminUrl,{headers:{'x-admin':'admin@example.test'}}),env,auth)).json();assert.equal(admin.leads.length,1);assert.equal(admin.leads[0].affiliateId,1);
  assert.equal((await affiliateWhatsappRoute(new Request(adminUrl,{method:'DELETE',headers:{'x-admin':'admin@example.test'}}),env,auth)).status,405);
 }finally{globalThis.fetch=original;db.close();}
});
