import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
test('delivery history groups welcome recipients and includes sent and pending payment notices per owner',async()=>{
 const sqlite=new DatabaseSync(':memory:');sqlite.exec(`
 CREATE TABLE crmClients(id INTEGER,name TEXT,email TEXT,birthDate TEXT);INSERT INTO crmClients VALUES(1,'One','one@example.test','1990-01-01'),(2,'Two','two@example.test','1990-01-02');
 CREATE TABLE scheduledMessages(id INTEGER,agentEmail TEXT,title TEXT,subject TEXT,audience TEXT,scheduledAt TEXT,occasion TEXT,monthNumber INTEGER,selectedClientIds TEXT,clientId INTEGER,isActive INTEGER,createdAt TEXT);INSERT INTO scheduledMessages VALUES(1,'owner@example.test','Boas-vindas à Affinity','Welcome one','individual',NULL,'custom',NULL,NULL,1,0,NULL),(2,'owner@example.test','Boas-vindas à Affinity','Welcome two','individual',NULL,'custom',NULL,NULL,2,0,NULL);
 CREATE TABLE automationDeliveries(id INTEGER,messageId INTEGER,clientId INTEGER,sentKey TEXT,sentAt TEXT);INSERT INTO automationDeliveries VALUES(1,1,1,'once','2026-10-07 12:30:00'),(2,2,2,'once','2026-10-08 12:30:00');
 CREATE TABLE crmDeliveryLogs(id INTEGER,clientId INTEGER,subject TEXT,clientName TEXT,recipientEmail TEXT,attemptedAt TEXT,errorMessage TEXT,agentEmail TEXT,status TEXT);
 CREATE TABLE clientEmails(id INTEGER,clientId INTEGER,agentEmail TEXT,direction TEXT,externalId TEXT,subject TEXT,sentAt TEXT);INSERT INTO clientEmails VALUES(1,1,'owner@example.test','sent','pay-1','Returned payment','2026-10-09 12:30:00'),(2,1,'other@example.test','sent','pay-other','Other','2026-10-09 12:30:00');
 CREATE TABLE crmActivities(clientId INTEGER,content TEXT);INSERT INTO crmActivities VALUES(1,'Aviso de pagamento encaminhado automaticamente. Referência: pay-1'),(1,'Aviso de pagamento encaminhado automaticamente. Referência: pay-other');
 CREATE TABLE agentMailboxEmails(id INTEGER,clientId INTEGER,subject TEXT,sentAt TEXT,actionDetail TEXT,agentEmail TEXT,direction TEXT,paymentStatus TEXT,actionStatus TEXT);INSERT INTO agentMailboxEmails VALUES(1,NULL,'Payment Returned','2026-10-08 13:48:46','Identificar cliente e apólice','owner@example.test','received','attention','needs_review'),(2,NULL,'Other','2026-10-08 13:48:46','','other@example.test','received','attention','needs_review');
 `);
 const db={prepare(sql){const stmt=sqlite.prepare(sql);let values=[];return {bind(...v){values=v;return this},async all(){return {results:stmt.all(...values)}}}},async batch(statements){return Promise.all(statements.map(s=>s.all()))}};
 const source=readFileSync(new URL('./worker/current-worker.js',import.meta.url),'utf8');const code=source.slice(source.indexOf('  if (name === "agent.deliveryLog")'),source.indexOf('  if (name === "agent.scheduleMessage")'));
 const invoke=new (Object.getPrototypeOf(async function(){}).constructor)('env','adminEmail','name','trpcResult',code);
 const rows=await invoke({DB:db},'owner@example.test','agent.deliveryLog',x=>x);const welcome=rows.filter(row=>row.title==='Boas-vindas à Affinity');assert.equal(welcome.length,1);assert.equal(welcome[0].recipients.length,2);assert.deepEqual(welcome[0].recipients.map(r=>r.sentAt),['2026-10-07 12:30:00','2026-10-08 12:30:00']);
 const payment=rows.filter(row=>row.title==='Pagamento devolvido');assert.equal(payment.length,2);assert.equal(payment.find(r=>r.status==='sent').clientId,1);assert.equal(payment.find(r=>r.status==='review').errorMessage,'Identificar cliente e apólice');sqlite.close();
});
