import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {leadFlowRoute,leadSchema,storeCentralContacts} from './worker/lead-flow.js';import {isUSPhone} from './worker/us-area-codes.js';
function fixture(){const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE adminAccounts(id INTEGER PRIMARY KEY,email TEXT,name TEXT,phone TEXT,accountType TEXT,status TEXT,isActive INTEGER,passwordHash TEXT,updatedAt TEXT);CREATE TABLE affiliates(id INTEGER PRIMARY KEY,email TEXT,name TEXT,phone TEXT,status TEXT,isActive INTEGER,passwordHash TEXT,updatedAt TEXT);CREATE TABLE crmClients(id INTEGER PRIMARY KEY,phone TEXT,whatsapp TEXT,status TEXT);CREATE TABLE agentPolicies(id INTEGER PRIMARY KEY,clientPhone TEXT,status TEXT,clientId INTEGER,agentEmail TEXT,policyNumber TEXT,product TEXT,premiumAmount REAL,premiumFrequency TEXT);`);for(let i=1;i<=2;i++)db.prepare('INSERT INTO adminAccounts VALUES(?,?,?,?,?,?,?,?,?)').run(i,'agent'+i+'@example.test','Agent '+i,'','agent','approved',1,'old','');db.prepare('INSERT INTO affiliates VALUES(?,?,?,?,?,?,?,?)').run(3,'affiliate@example.test','Affiliate','','approved',1,'old','');const prepare=sql=>{let args=[];return {bind(...v){args=v;return this},async first(){return db.prepare(sql).get(...args)},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}}}}};db.exec("CREATE TABLE staffFlowSettings(key TEXT PRIMARY KEY,value TEXT NOT NULL);INSERT INTO staffFlowSettings VALUES('legacySnapshot','fixture-cutoff');");const env={DB:{prepare,batch:async queries=>{db.exec('BEGIN');try{const out=[];for(const q of queries)out.push(await q.run());db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}},WHATSAPP_BRIDGE_URL:'https://bridge.example.test',WHATSAPP_BRIDGE_SECRET:'a'.repeat(48)},auth={email:async r=>r.headers.get('x-user'),affiliate:async r=>Number(r.headers.get('x-affiliate'))||null,access:async email=>email==='admin@example.test'?{isMaster:true}:{account:db.prepare('SELECT * FROM adminAccounts WHERE email=?').get(email)},compare:async(p,h)=>p===h,hash:async p=>'hashed:'+p};const call=(kind,action,input,user='agent1@example.test',method)=>leadFlowRoute(new Request('https://www.affinityfc.org/api/'+kind+'/'+action,{method:method||(input?'POST':'GET'),headers:{'x-user':user,'x-affiliate':'3',...(input?{origin:'https://www.affinityfc.org','content-type':'application/json'}:{})},...(input?{body:JSON.stringify(input)}:{})}),env,auth);return {db,env,auth,call};}
test('US distribution distinguishes Canada, Caribbean, international and unknown numbers',()=>{assert(isUSPhone('+16175550100'));for(const p of ['+14165550100','+12425550100','+5511999999999','+18005550100','+15555550100'])assert(!isUSPhone(p));});
test('global deduplication keeps all sources and priorities; assignment and outcome enforce one lead and global suppression',async()=>{const {db,env,call}=fixture();await leadSchema(env);const c={phone:'+16175550100',name:'Name',groups:[{id:'123456789@g.us',name:'Work'}]};await storeCentralContacts(env,{owner:'affiliate:3',kind:'affiliate',name:'Affiliate',email:'affiliate@example.test'},[c,{phone:'+5511999999999',name:'International'},{phone:'+16175550101',name:'Next'}]);await storeCentralContacts(env,{owner:'agent:agent1@example.test',kind:'agent',name:'Agent 1',email:'agent1@example.test'},[{...c,name:'Other'}]);assert.equal(db.prepare('SELECT count(*) AS c FROM centralLeads').get().c,3);assert.equal(db.prepare('SELECT count(*) AS c FROM centralLeadSources WHERE phone=?').get(c.phone).c,2);
 assert.equal((await call('agent','lead-queue/next',{})).status,409);for(const i of [1,2])db.prepare('INSERT INTO staffOnboarding VALUES(?,?,?,?,?,?,?)').run('agent:agent'+i+'@example.test','agent','','/staff-avatar-1.svg',1,1,'');
 assert.equal((await call('affiliate','contact-import/priority',{phones:[c.phone]})).status,200);
 assert.equal((await call('admin','central-leads/assign',{phones:['+5511999999999'],allAgents:true},'admin@example.test')).status,400);
 assert.equal((await call('admin','central-leads/assign',{phones:[c.phone,'+16175550101'],allAgents:true},'admin@example.test')).status,200);
 const a=await(await call('agent','lead-queue/next',{})).json();assert.equal(a.lead.phone,c.phone);assert.equal(a.lead.sources.length,2);assert.equal((await(await call('agent','lead-queue/next',{})).json()).lead.phone,c.phone);
 const b=await(await call('agent','lead-queue/next',{},'agent2@example.test')).json();assert.equal(b.lead.phone,'+16175550101');
 assert.equal((await call('agent','lead-queue/result',{phone:c.phone,response:'Sem resposta',attempts:0,stage:'Sem interesse',note:'test'})).status,400);
 assert.equal((await call('agent','lead-queue/result',{phone:c.phone,response:'Respondeu',attempts:1,stage:'Sem interesse',note:'No interest'})).status,200);
 assert.equal(db.prepare('SELECT suppressed FROM centralLeads WHERE phone=?').get(c.phone).suppressed,1);
 assert.equal((await call('admin','central-leads/assign',{phones:[c.phone],allAgents:true},'admin@example.test')).status,409);
 assert.equal((await call('agent','lead-queue/result',{phone:c.phone,response:'Respondeu',attempts:1,stage:'Interesse',note:'again'})).status,409);
 const list=await(await call('admin','central-leads/list?category=Sem%20interesse',null,'admin@example.test')).json();assert.equal(list.leads.length,1);assert.equal(list.leads[0].history[0].attempts,1);
 assert.equal((await call('admin','central-leads/list',null,'agent1@example.test')).status,401);
 db.close();});
test('active clients, employee category and excluded groups are hidden from every agent',async()=>{const {db,env,call}=fixture();await leadSchema(env);const source={owner:'affiliate:3',kind:'affiliate',name:'Affiliate',email:'affiliate@example.test'},contacts=[{phone:'+16175550100',name:'Work',groups:[{id:'123456789@g.us',name:'Internal'}]},{phone:'+16175550101',name:'Client'},{phone:'+16175550102',name:'Employee'},{phone:'+16175550103',name:'Policy'},{phone:'+14165550100',name:'Canadian'}];await storeCentralContacts(env,source,contacts);db.prepare('INSERT INTO crmClients VALUES(?,?,?,?)').run(1,'(617) 555-0101',null,'client');db.prepare('INSERT INTO crmClients VALUES(?,?,?,?)').run(2,'+16175550102',null,'agent');db.prepare('INSERT INTO agentPolicies(id,clientPhone,status,clientId) VALUES(?,?,?,?)').run(1,'+16175550103','active',null);
 assert.equal((await call('admin','central-leads/exclude-group',{groupId:'123456789@g.us',name:'Internal'},'admin@example.test')).status,200);
 for(const [phone,stage] of [['+16175550100','Grupo excluído'],['+16175550101','Cliente ativo'],['+16175550102','Agente'],['+16175550103','Cliente ativo']]){const l=db.prepare('SELECT * FROM centralLeads WHERE phone=?').get(phone);assert.equal(l.stage,stage);assert.equal(l.suppressed,1)}
 assert.equal((await call('admin','central-leads/assign',{phones:['+16175550100'],allAgents:true},'admin@example.test')).status,409);
 assert.equal((await call('admin','central-leads/exclude-group',{groupId:'123456789@g.us',excluded:false},'admin@example.test')).status,200);assert.equal(db.prepare('SELECT suppressed FROM centralLeads WHERE phone=?').get('+16175550100').suppressed,0);
 const intl=await(await call('admin','central-leads/list?category=international',null,'admin@example.test')).json();assert.equal(intl.leads.length,1);assert.equal(intl.leads[0].phone,'+14165550100');db.close();});
test('first access requires profile, current password, full import acknowledgement, and completion; priorities never restrict import',async()=>{const {db,env,call}=fixture();const original=globalThis.fetch;globalThis.fetch=async url=>{const p=new URL(url).pathname;return Response.json(p==='/all-contacts'?{contacts:[{phone:'+16175550100',name:'US'},{phone:'+5511999999999',name:'International'}],unresolved:0}:p==='/status'?{state:'ready'}:{ok:true})};try{
 assert.equal((await call('affiliate','contact-import/connect',{consent:true})).status,409);
 const profile={phone:'+16175550104',avatar:'/staff-avatar-6.svg',password:'newpassword123',currentPassword:'bad'};assert.equal((await call('affiliate','onboarding/profile',profile)).status,400);profile.currentPassword='old';assert.equal((await call('affiliate','onboarding/profile',profile)).status,200);assert.equal(db.prepare('SELECT passwordHash FROM affiliates').get().passwordHash,'hashed:newpassword123');
 assert.equal((await call('affiliate','onboarding/finish',{})).status,409);assert.equal((await call('affiliate','contact-import/connect',{consent:false})).status,400);assert.equal((await call('affiliate','contact-import/connect',{consent:true})).status,200);const r=await(await call('affiliate','contact-import/sync',{})).json();assert.equal(r.count,2);assert.equal(r.state,'done');await call('affiliate','contact-import/priority',{phones:['+16175550100']});assert.equal(db.prepare('SELECT count(*) AS c FROM centralLeads').get().c,2);assert.equal((await call('affiliate','onboarding/finish',{})).status,200);assert.equal((await(await call('affiliate','onboarding/status')).json()).completed,true);
 assert.equal((await call('affiliate','contact-import/delete',{})).status,405);const invalid=new Request('https://www.affinityfc.org/api/affiliate/onboarding/profile',{method:'POST',headers:{'x-affiliate':'3','content-type':'application/json',origin:'https://evil.test'},body:'{}'});assert.equal((await leadFlowRoute(invalid,env,fixture().auth)).status,403);
 }finally{globalThis.fetch=original;db.close()}});
test('existing phone, password, photo and WhatsApp skip setup; incomplete accounts retain existing credentials and photo',async()=>{const {db,env,call}=fixture();db.exec('CREATE TABLE agentPublicProfiles(agentEmail TEXT,photoUrl TEXT)');db.prepare('INSERT INTO agentPublicProfiles VALUES(?,?)').run('agent1@example.test','https://example.test/existing-photo.png');db.prepare('UPDATE adminAccounts SET phone=? WHERE email=?').run('+16175550199','agent1@example.test');const old=globalThis.fetch;let ready=true;globalThis.fetch=async()=>Response.json({state:ready?'ready':'disconnected'});try{let d=await(await call('agent','onboarding/status')).json();assert.equal(d.completed,true);assert.equal(d.passwordSet,true);assert.equal(d.avatar,'https://example.test/existing-photo.png');assert.equal(d.needsImport,true);assert.equal(db.prepare('SELECT passwordHash FROM adminAccounts WHERE id=1').get().passwordHash,'old');ready=false;d=await(await call('agent','onboarding/status',null,'agent2@example.test')).json();assert.equal(d.completed,false);assert.equal(d.passwordSet,true);assert.equal((await call('agent','onboarding/profile',{phone:'+16175550198'},'agent2@example.test')).status,200);assert.equal(db.prepare('SELECT passwordHash FROM adminAccounts WHERE id=2').get().passwordHash,'old');d=await(await call('agent','onboarding/status',null,'agent2@example.test')).json();assert.equal(d.profileSaved,true);assert.equal(d.completed,false);}finally{globalThis.fetch=old;db.close()}});
test('opening the central twice never replays completed legacy migration or overwrites current lead stages',async()=>{const {db,env,call}=fixture();await leadSchema(env);db.exec("CREATE TABLE whatsappLeads(id INTEGER PRIMARY KEY,phone TEXT,name TEXT,stage TEXT,owner TEXT,updatedAt TEXT);CREATE TABLE whatsappLeadGroups(owner TEXT,leadId INTEGER,groupId TEXT,groupName TEXT);INSERT INTO whatsappLeads VALUES(1,'+16175550100','Legacy','Importados','agent1@example.test','2026-10-09');");assert.equal((await call('admin','central-leads/list',null,'admin@example.test')).status,200);db.exec("UPDATE centralLeads SET stage='Interesse';CREATE TRIGGER reject_legacy_replay BEFORE INSERT ON centralLeads BEGIN SELECT RAISE(ABORT,'Legacy migration replayed');END;");assert.equal((await call('admin','central-leads/list',null,'admin@example.test')).status,200);assert.equal(db.prepare('SELECT stage FROM centralLeads').get().stage,'Interesse');assert.equal(db.prepare("SELECT count(*) AS c FROM centralLeadMigrations WHERE version='legacy-central-v1'").get().c,1);db.close();});
test('agent imports are immediately visible to importer and admin; other agents require admin designation',async()=>{const {db,env,call}=fixture();await leadSchema(env);for(const i of [1,2])db.prepare('INSERT INTO staffOnboarding VALUES(?,?,?,?,?,?,?)').run('agent:agent'+i+'@example.test','agent','','/staff-avatar-1.svg',1,1,'');const phone='+16175550188';await storeCentralContacts(env,{owner:'agent:agent1@example.test',kind:'agent',name:'Agent 1',email:'agent1@example.test'},[{phone,name:'Imported'},{phone:'+5511999999999',name:'International'}]);assert.equal((await(await call('admin','central-leads/list',null,'admin@example.test')).json()).total,1);assert.equal((await(await call('agent','lead-queue/next',{},'agent2@example.test')).json()).lead,null);assert.equal((await call('admin','central-leads/assign',{phones:[phone],allAgents:true},'agent1@example.test')).status,401);assert.equal((await(await call('agent','lead-queue/next',{})).json()).lead.phone,phone);assert.equal(db.prepare('SELECT count(*) AS c FROM centralLeadAssignments').get().c,1);assert.equal((await call('admin','central-leads/assign',{phones:[phone],agents:['agent2@example.test']},'admin@example.test')).status,200);db.close();});
test('agent work-group exclusions affect only that agent queue, preserve admin sources and reject staff downloads',async()=>{const {db,env,call}=fixture();await leadSchema(env);for(const i of [1,2])db.prepare('INSERT INTO staffOnboarding VALUES(?,?,?,?,?,?,?)').run('agent:agent'+i+'@example.test','agent','','/staff-avatar-1.svg',1,1,'');const phone='+16175550190',group='123456789@g.us';await storeCentralContacts(env,{owner:'agent:agent1@example.test',kind:'agent',name:'Agent 1',email:'agent1@example.test'},[{phone,name:'Person',groups:[{id:group,name:'Work'}]}]);assert.equal((await call('admin','central-leads/assign',{phones:[phone],agents:['agent2@example.test']},'admin@example.test')).status,200);assert.equal((await call('agent','contact-import/exclude-group',{groupId:group,excluded:true})).status,200);assert.equal((await(await call('agent','lead-queue/next',{})).json()).lead,null);assert.equal((await(await call('admin','central-leads/list',null,'admin@example.test')).json()).leads[0].sources[0].sourceName,'Agent 1');assert.equal((await(await call('agent','lead-queue/next',{},'agent2@example.test')).json()).lead.phone,phone);assert.equal((await call('agent','contact-import/exclude-group',{groupId:group},'agent2@example.test')).status,404);assert.equal((await call('agent','contact-import/export')).status,403);assert.equal((await call('affiliate','contact-import/export')).status,403);assert.equal((await call('admin','central-leads/export?category=all',null,'admin@example.test')).status,200);await call('agent','contact-import/exclude-group',{groupId:group,excluded:false});assert.equal((await(await call('agent','contact-import/groups')).json()).groups[0].excluded,0);assert.equal(db.prepare('SELECT suppressed FROM centralLeads WHERE phone=?').get(phone).suppressed,0);db.close();});
test('contact panel filters by originating group with accurate totals and account isolation',async()=>{const {db,env,call}=fixture();await storeCentralContacts(env,{owner:'agent:agent1@example.test',kind:'agent',email:'agent1@example.test'},[{phone:'+16175550100',name:'Work',groups:[{id:'123456789@g.us',name:'Work group'}]},{phone:'+16175550101',name:'Personal',groups:[]}]);await storeCentralContacts(env,{owner:'agent:agent2@example.test',kind:'agent',email:'agent2@example.test'},[{phone:'+16175550102',name:'Other',groups:[{id:'123456789@g.us',name:'Work group'}]}]);assert.equal((await(await call('agent','contact-import/contacts')).json()).total,2);const filtered=await(await call('agent','contact-import/contacts?group=123456789%40g.us')).json();assert.equal(filtered.total,1);assert.equal(filtered.contacts[0].name,'Work');assert.equal((await(await call('agent','contact-import/groups')).json()).groups[0].contacts,1);db.close();});
test('saving a full page of 100 contact priorities respects D1 binding limits',async()=>{const {db,env,call}=fixture();await leadSchema(env);const contacts=Array.from({length:100},(_,i)=>({phone:'+1617555'+String(i).padStart(4,'0'),name:'Fixture '+i}));await storeCentralContacts(env,{owner:'agent:agent1@example.test',kind:'agent',email:'agent1@example.test'},contacts);const original=env.DB.prepare;env.DB.prepare=sql=>{const stmt=original(sql),bind=stmt.bind;stmt.bind=function(...args){assert(args.length<=100,'D1 parameter limit exceeded');return bind.apply(this,args)};return stmt;};assert.equal((await call('agent','contact-import/priority',{phones:contacts.map(c=>c.phone)})).status,200);assert.equal(db.prepare('SELECT count(*) AS n FROM centralLeadSources WHERE priority=1').get().n,100);db.close();});

test('issued closing requires confirmed sale, preserves payout snapshot and blocks other agents',async()=>{const {db,env,call}=fixture();await leadSchema(env);db.prepare('INSERT INTO staffOnboarding VALUES(?,?,?,?,?,?,?)').run('agent:agent1@example.test','agent','','/staff-avatar-1.svg',1,1,'');const phone='+16175550100';await storeCentralContacts(env,{owner:'agent:agent1@example.test',kind:'agent',email:'agent1@example.test'},[{phone,name:'Fixture'}]);await call('agent','lead-queue/next',{});const outcome={phone,response:'Respondeu',attempts:1,stage:'Emitida',note:'Confirmed fixture'};assert.equal((await call('agent','lead-queue/result',outcome)).status,400);const {readRates,saveRates}=await import('./worker/affiliate-rates.js');const rates=await readRates(env);assert(rates.every(r=>r.payout===null));await saveRates(env,{rates:rates.map(r=>({key:r.key,payout:r.key==='iul1'?25:null}))},'admin@example.test');outcome.sale={product:'IUL',category:'iul1',monthlyPremium:200,confirmed:true};assert.equal((await call('agent','lead-queue/result',outcome,'agent2@example.test')).status,409);assert.equal((await call('agent','lead-queue/result',outcome)).status,200);const c=db.prepare('SELECT * FROM centralLeadClosures').get();assert.equal(c.product,'IUL tipo 1');assert.equal(c.monthlyPremiumCents,20000);assert.equal(c.referencePayoutCents,2500);assert.equal(db.prepare('SELECT suppressed FROM centralLeads').get().suppressed,1);await saveRates(env,{rates:rates.map(r=>({key:r.key,payout:50}))},'admin@example.test');assert.equal(db.prepare('SELECT referencePayoutCents FROM centralLeadClosures').get().referencePayoutCents,2500);db.close();});

test('agent numbers can remain pending with reminders after fifteen days and Rafael fallback',async()=>{const {db,env,call}=fixture();await leadSchema(env);const {saveRegistration,registrationStatus}=await import('./worker/lead-flow.js');const {numberDefaults,applicationAgentDetails}=await import('./worker/marketing-obligations.js');await numberDefaults(env,{number:'RAFAEL-FIXTURE'},'admin@example.test');await saveRegistration(env,'agent:agent1@example.test',{numberPending:true},1000);let status=await registrationStatus(env,'agent:agent1@example.test',1001);assert.equal(status.numberReminderDue,false);assert.equal(status.effectiveAgentNumber,'RAFAEL-FIXTURE');status=await registrationStatus(env,'agent:agent1@example.test',1000+15*86400000);assert.equal(status.numberReminderDue,true);await saveRegistration(env,'agent:agent1@example.test',{agentNumber:'OWN-123'},1000);status=await registrationStatus(env,'agent:agent1@example.test',Date.now());assert.equal(status.numberReminderDue,false);assert.equal(status.effectiveAgentNumber,'OWN-123');assert.equal((await applicationAgentDetails(env,'agent1@example.test')).name,'Agent 1');await assert.rejects(saveRegistration(env,'agent:agent1@example.test',{agentNumber:'CHANGED'}),/não pode ser alterado/);await assert.rejects(saveRegistration(env,'agent:agent1@example.test',{numberPending:true}),/não pode ser alterado/);assert.equal((await registrationStatus(env,'agent:agent1@example.test')).agentNumber,'OWN-123');assert.equal((await call('agent','onboarding/agent-number',{numberPending:true},'agent2@example.test')).status,200);assert.equal((await call('affiliate','onboarding/agent-number',{numberPending:true})).status,405);db.close();});

test('marketing obligations use annual ten percent, admin beneficiary and payer-isolated payment reporting',async()=>{const {db,env,call}=fixture();await leadSchema(env);const {ratesSchema,referenceBands,saveRates}=await import('./worker/affiliate-rates.js');const {listObligations,selectBeneficiary,reportPayment,confirmPayment}=await import('./worker/marketing-obligations.js');await ratesSchema(env);const phone='+16175550100';await storeCentralContacts(env,{owner:'agent:agent1@example.test',kind:'agent',email:'agent1@example.test',name:'Payer'},[{phone,name:'Fixture'}]);await storeCentralContacts(env,{owner:'agent:agent2@example.test',kind:'agent',email:'agent2@example.test',name:'Referrer'},[{phone,name:'Fixture'}]);await storeCentralContacts(env,{owner:'affiliate:3',kind:'affiliate',email:'affiliate@example.test',name:'Affiliate'},[{phone,name:'Fixture'}]);db.prepare('INSERT INTO centralLeadClosures(phone,agent,product,monthlyPremiumCents,bandKey) VALUES(?,?,?,?,?)').run(phone,'agent1@example.test','Term',10000,'term150');let rows=await listObligations(env);assert.equal(rows[0].annualPremiumCents,120000);assert.equal(rows[0].sources.length,2);await assert.rejects(selectBeneficiary(env,{phone,owner:'agent:agent1@example.test'},'admin'),/fonte válida/);await selectBeneficiary(env,{phone,owner:'affiliate:3'},'admin');assert.equal((await listObligations(env,'agent1@example.test'))[0].status,'awaiting_rate');await saveRates(env,{rates:referenceBands.map(r=>({key:r.key,payout:25}))},'admin');await selectBeneficiary(env,{phone,owner:'affiliate:3'},'admin');assert.equal((await listObligations(env,'agent1@example.test'))[0].amountCents,2500);await selectBeneficiary(env,{phone,owner:'agent:agent2@example.test'},'admin');rows=await listObligations(env,'agent1@example.test');assert.equal(rows[0].amountCents,12000);assert.equal(rows[0].beneficiaryName,'Referrer');assert.equal(rows[0].sources,undefined);assert.equal((await listObligations(env,'agent2@example.test')).length,0);const payment={phone,paidAt:'2020-01-01',reference:'Fixture-only receipt'};await assert.rejects(reportPayment(env,payment,'agent2@example.test'),/indisponível/);await reportPayment(env,payment,'agent1@example.test');await assert.rejects(selectBeneficiary(env,{phone,owner:'affiliate:3'},'admin'),/alterada/);await confirmPayment(env,{phone},'admin');assert.equal((await listObligations(env,'agent1@example.test'))[0].status,'paid');assert.equal((await call('agent','marketing/list',null,'agent2@example.test')).status,200);assert.equal((await(await call('agent','marketing/list',null,'agent2@example.test')).json()).obligations.length,0);db.close();});

test('global excluded membership wins over other groups, sources and all list filters, and can be restored',async()=>{const {db,env,call}=fixture();await leadSchema(env);const phone='+16175550100',work='123456789@g.us',publicGroup='987654321@g.us';await storeCentralContacts(env,{owner:'affiliate:3',kind:'affiliate',email:'affiliate@example.test'},[{phone,name:'Fixture',groups:[{id:work,name:'Work'},{id:publicGroup,name:'Public'}]}]);await storeCentralContacts(env,{owner:'agent:agent1@example.test',kind:'agent',email:'agent1@example.test'},[{phone,name:'Fixture',groups:[{id:publicGroup,name:'Public'}]}]);assert.equal((await call('admin','central-leads/exclude-groups',{groups:[{id:work,name:'Work',excluded:true}]},'admin@example.test')).status,200);assert.equal((await(await call('admin','central-leads/list?category=all',null,'admin@example.test')).json()).total,0);assert.equal((await(await call('agent','contact-import/contacts?group='+encodeURIComponent(publicGroup))).json()).total,0);assert.equal((await(await call('admin','central-leads/list?category=Grupo%20exclu%C3%ADdo',null,'admin@example.test')).json()).total,1);await call('admin','central-leads/exclude-groups',{groups:[{id:work,name:'Work',excluded:false}]},'admin@example.test');assert.equal((await(await call('agent','contact-import/contacts')).json()).total,1);db.close();});
test('queue rotates sources then groups and preserves one active reservation',async()=>{const {db,env}=fixture();await leadSchema(env);const {reserveFairLead}=await import('./worker/queue-fairness.js');const sources=[{owner:'affiliate:3',kind:'affiliate',email:'affiliate@example.test'},{owner:'agent:agent1@example.test',kind:'agent',email:'agent1@example.test'},{owner:'agent:agent2@example.test',kind:'agent',email:'agent2@example.test'}];for(let i=0;i<3;i++){await storeCentralContacts(env,sources[i],Array.from({length:4},(_,n)=>({phone:'+16175550'+i+n+'0',name:'Fixture',groups:[{id:n%2?'987654321@g.us':'123456789@g.us',name:n%2?'Group 2':'Group 1'}]})));}for(const row of db.prepare('SELECT phone FROM centralLeads').all())db.prepare('INSERT OR IGNORE INTO centralLeadAssignments(phone,agent,assignedBy) VALUES(?,?,?)').run(row.phone,'agent1@example.test','admin');const turns=[],groups=[];for(let i=0;i<6;i++){await reserveFairLead(env,'agent1@example.test','agent:agent1@example.test','',1000+i);const lead=db.prepare('SELECT phone FROM centralLeads WHERE leaseOwner=?').get('agent1@example.test');assert(lead);const turn=db.prepare("SELECT sourceOwner,groupKey FROM centralQueueRotation WHERE agent=? AND groupKey<>'*' ORDER BY lastServedAt DESC LIMIT 1").get('agent1@example.test');turns.push(turn.sourceOwner);groups.push(turn.groupKey);await reserveFairLead(env,'agent1@example.test','agent:agent1@example.test','',1000+i);assert.equal(db.prepare('SELECT count(*) n FROM centralLeads WHERE leaseOwner=?').get('agent1@example.test').n,1);db.prepare('UPDATE centralLeads SET suppressed=1,leaseOwner=NULL,leaseUntil=0 WHERE phone=?').run(lead.phone);}assert.deepEqual(turns,[sources[0].owner,sources[1].owner,sources[2].owner,sources[0].owner,sources[1].owner,sources[2].owner]);assert.notEqual(groups[0],groups[3]);db.close();});

test('policy appearing without queue closing links lead and obligation once, preserves sources and flags incomplete data',async()=>{const {db,env}=fixture();await leadSchema(env);const {syncPolicyLeadLinks}=await import('./worker/policy-lead-links.js');const {listObligations}=await import('./worker/marketing-obligations.js');const phone='+16175550100';await storeCentralContacts(env,{owner:'affiliate:3',kind:'affiliate',email:'affiliate@example.test',name:'Affiliate'},[{phone,name:'Fixture'}]);db.prepare('INSERT INTO agentPolicies(id,clientPhone,status,agentEmail,policyNumber,product,premiumAmount,premiumFrequency) VALUES(?,?,?,?,?,?,?,?)').run(1,'(617) 555-0100','active','agent1@example.test','TEST-001','Term',1475,'annual');await syncPolicyLeadLinks(env,'agent1@example.test');await syncPolicyLeadLinks(env,'agent1@example.test');const obligations=await listObligations(env,'agent1@example.test');assert.equal(obligations.length,1);assert.equal(obligations[0].annualPremiumCents,147500);assert.equal(obligations[0].policyNumbers,'TEST-001');assert.equal(obligations[0].status,'awaiting_admin');assert.equal(db.prepare('SELECT count(*) n FROM centralLeadOutcomes').get().n,0);assert.equal(db.prepare('SELECT count(*) n FROM centralLeadSources').get().n,1);assert.equal(db.prepare('SELECT suppressed FROM centralLeads').get().suppressed,1);assert.equal(db.prepare('SELECT count(*) n FROM centralLeadClosures').get().n,1);db.prepare('INSERT INTO agentPolicies(id,clientPhone,status,agentEmail,policyNumber,product,premiumAmount) VALUES(?,?,?,?,?,?,?)').run(2,phone,'active','agent2@example.test','TEST-002','Unknown',0);await syncPolicyLeadLinks(env);assert.equal(db.prepare('SELECT status FROM centralPolicyLeadLinks WHERE policyId=2').get().status,'needs_review');assert.equal(db.prepare('SELECT payer FROM marketingObligations').get().payer,'agent1@example.test');db.close();});
test('Five Rings reminders repeat every fifteen days and only Admin can exempt registered agents',async()=>{
const {db,env}=fixture();const {fiveRingsRequirement,postponeFiveRings,adminFiveRingsRequirements}=await import('./worker/five-rings-onboarding.js');
const email='agent1@example.test',now=100000;
assert.equal((await fiveRingsRequirement(env,email,now)).fiveRingsReminderDue,true);
await postponeFiveRings(env,email,now);
assert.equal((await fiveRingsRequirement(env,email,now+14*86400000)).fiveRingsReminderDue,false);
assert.equal((await fiveRingsRequirement(env,email,now+15*86400000)).fiveRingsReminderDue,true);
await postponeFiveRings(env,email,now+15*86400000);
assert.equal((await fiveRingsRequirement(env,email,now+16*86400000)).fiveRingsReminderDue,false);
await adminFiveRingsRequirements(env,{email,exempt:true},'admin@example.test');
assert.equal((await fiveRingsRequirement(env,email,now+100*86400000)).fiveRingsReminderDue,false);
await assert.rejects(()=>adminFiveRingsRequirements(env,{email:'unknown@example.test',exempt:true},'admin@example.test'));
await adminFiveRingsRequirements(env,{email,exempt:false},'admin@example.test');
db.exec("CREATE TABLE agentFiveRingsConnections(agentEmail TEXT,portalEmail TEXT,encryptedPassword TEXT)");
db.prepare('INSERT INTO agentFiveRingsConnections VALUES(?,?,?)').run(email,email,'encrypted-fixture');
assert.equal((await fiveRingsRequirement(env,email,now)).fiveRingsConfigured,true);
assert.equal((await fiveRingsRequirement(env,email,now)).fiveRingsReminderDue,false);
db.close();
});
test('Five Rings portal gate runs every other Wednesday and honors deferment and Admin exemption',async()=>{
const {db,env}=fixture();const {fiveRingsRequirement,markPortalFiveRingsSync,postponeFiveRings,adminFiveRingsRequirements}=await import('./worker/five-rings-onboarding.js');
const email='agent1@example.test',at=d=>Date.parse(d+'T12:00:00-04:00');
assert.equal((await fiveRingsRequirement(env,email,at('2026-10-13'))).fiveRingsSyncDue,false);
assert.equal((await fiveRingsRequirement(env,email,at('2026-10-14'))).fiveRingsSyncDue,true);
await markPortalFiveRingsSync(env,email,at('2026-10-14'));
assert.equal((await fiveRingsRequirement(env,email,at('2026-10-21'))).fiveRingsSyncDue,false);
assert.equal((await fiveRingsRequirement(env,email,at('2026-10-28'))).fiveRingsSyncDue,true);
await postponeFiveRings(env,email,at('2026-10-28'));
assert.equal((await fiveRingsRequirement(env,email,at('2026-11-04'))).fiveRingsSyncDue,false);
await adminFiveRingsRequirements(env,{email,exempt:true},'admin@example.test');
assert.equal((await fiveRingsRequirement(env,email,at('2026-12-02'))).fiveRingsSyncDue,false);db.close();
});
test('agent theme defaults to light, persists per account and rejects invalid values',async()=>{
const {db,call}=fixture();
assert.equal((await(await call('agent','onboarding/theme')).json()).theme,'light');
assert.equal((await call('agent','onboarding/theme',{theme:'dark'})).status,200);
assert.equal((await(await call('agent','onboarding/theme')).json()).theme,'dark');
assert.equal((await(await call('agent','onboarding/theme',null,'agent2@example.test')).json()).theme,'light');
assert.equal((await call('agent','onboarding/theme',{theme:'automatic'})).status,400);
assert.equal((await(await call('agent','onboarding/theme')).json()).theme,'dark');
assert.equal((await call('agent','onboarding/theme',{theme:'light'})).status,200);
assert.equal((await(await call('agent','onboarding/theme')).json()).theme,'light');
db.close();
});
